### ISSUE TITLE
user accounts not showing in Accounts list

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#107]
Daniella Lowenberg made an account but it doesn't show up in the Accounts list

![Screen Shot 2020-07-20 at 1 35 44 PM](https://user-images.githubusercontent.com/49563305/87985635-c5bfbc80-ca90-11ea-8d88-b4ec64dda2fd.png)

Is there a limit on the number of accounts that can be displayed on that page?

**Comment by NicolasKieffer** [comment]
Yes, there is a maximum of 20 accounts displayed (by default).
I will add a form to set number of accounts (or documents) displayed.

Note : You can already set it *manually* by adding a **limit** parameter at the end of your URL
Example : to display 30 accounts, URL would be /backoffice/accounts?limit=30

**Comment by NicolasKieffer** [comment]
Bug fixed (screen of localhost version) :
![image](https://user-images.githubusercontent.com/16922410/88083868-d8ff8480-cb83-11ea-86d3-83a263907531.png)

You can set limit (or select role) with "custom search" form.

Note : "results counter" of displayed list of accounts (or documents) has been added
(*MyDocuments*, *All documents* and *Accounts* sections)

**Comment by timvines19** [comment]
great, please add this to the Prod version

**Comment by NicolasKieffer** [comment]
reopen (automatic closed after merge)
