### ISSUE TITLE
upload slow or doesn't work for Standard Users

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#108]
It's hard to recreate this error, but uploading a document is really slow at the moment (>30 seconds) and leads to 'Unknown error' quite a lot of the time. Retrying the same document sometimes works

This is a major problem because there's a steady stream of potential customers who are trying DataSeer out but finding that it doesn't work...

**Comment by NicolasKieffer** [comment]
@kermitt2 This could come from dataseer-ml web service? (Any infos in logs?) Or maybe from server?

Upload form "only" send PDF to dataseer-ml web service.

**Comment by timvines19** [comment]
Was better for a while but happening again today

**Comment by kermitt2** [comment]
I've updated the DNS and default access to the dataseer ML service, it think it should solve the issue.

**Comment by kermitt2** [comment]
Does it still occur ?

**Comment by timvines19** [comment]
Seems back to normal - which is still a bit slow (20secs)
