### ISSUE TITLE
restrict annotators to particular sets of documents

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#109]
Annotators will generally be data managers or data curators working for a partner organisation (e.g. Springer-Nature or Global Water Futures).

At present, a GWF data manager can see all the documents, even potentially confidential ones uploaded by SN authors, and vice versa for SN data curators.

How can we address this? One option is to create a different instance of the Production service for each partner org, but that could become unmanageable very quickly.

**Comment by NicolasKieffer** [comment]
We could add a property "organisation" on each "account" and then restrict documents visibility depending of user "organisation". 
Curator could "manage" this property via "Accounts" section.

**Comment by timvines19** [comment]
That's a great suggestion

**Comment by NicolasKieffer** [comment]
Feature done :

Curators can now set organisation of users and manage organisations.

Notes :
- set organisation to an account will set organisationt all documents (of this account) too.
- delete an organisation will set documents & accounts (of this organisation) to "None".

Should i display account organisation (hidden by default)?

**UI updates :**

Accounts management UI (curators only) :
![image](https://user-images.githubusercontent.com/16922410/90411171-a32ebc80-e0ab-11ea-8368-9186a377a541.png)

Documents management UI :
- curators (will see all documents of all organisations)
![image](https://user-images.githubusercontent.com/16922410/90411211-b6418c80-e0ab-11ea-95db-ada901b76274.png)

- annotators (will see only documents of his organisation)
![image](https://user-images.githubusercontent.com/16922410/90411095-8befcf00-e0ab-11ea-87aa-9d0cd527f8ca.png)

Organisations management UI (curators only) :
![image](https://user-images.githubusercontent.com/16922410/90411282-d40ef180-e0ab-11ea-9b81-a2318e097eaa.png)

**Comment by timvines19** [comment]
Need also to allow users to select organization at the Sign Up phase, perhaps from a drop down menu

**Comment by NicolasKieffer** [comment]
Should i let "None" option in Organisation selection on "sign up" form? (case Organisation does not exist yet?)

**Comment by timvines19** [comment]
Please do add 'None' as an organisation option

**Comment by timvines19** [comment]
Has this been deployed to the Production server?
