### ISSUE TITLE
The UI site is 'not secure'...

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#116]
which some users may find worrying

![Screen Shot 2020-08-10 at 2 09 11 PM](https://user-images.githubusercontent.com/49563305/89831883-6abf3980-db13-11ea-8f2a-a3fc2417c0d7.png)

![Screen Shot 2020-08-10 at 2 12 43 PM](https://user-images.githubusercontent.com/49563305/89831986-99d5ab00-db13-11ea-99ac-b7c0882f1d46.png)

**Comment by NicolasKieffer** [comment]
@kermitt2 To disable this alert, server must use https protocol.

**Comment by kermitt2** [comment]
Yes I have to put all the science-miner cloud services under https, I have a ssl certificate via my provider, and everything is already proxified via kongapi, 
https://docs.konghq.com/2.1.x/configuration/#nginx-section 
https://docs.konghq.com/2.1.x/configuration/#ssl_cert

**Comment by kermitt2** [comment]
looks good... the certificate for the subdomain from Let's encrypt lasts 3 months and should be renewed automatically 1 month before via the cron table of the server... so le't see in 3 months if it still works :)
