### ISSUE TITLE
make scroll bar visible for longer on All Documents

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#117]
The quickest way to get down to the bottom of the page in All Documents is by dragging the dot on the scroll bar, but it's hard to get hold of the dot because it's only visible when the page is being moved up and down with the cursors.

Please make the scroll bar visible for longer after the page has been scrolled up or down

**Comment by NicolasKieffer** [comment]
Scrollbar depend on browser.
Should i add buttons "page up" "page down" to get "custom scroll"?

**Comment by timvines19** [comment]
Please do add these buttons
