### ISSUE TITLE
Integrate the UI with Intercom to enable live chat help

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#118]
Here's the link to the section where we can identify logged in users in the Messenger chat:

XXX

**Comment by kermitt2** [comment]
I got nice feedback for https://crisp.chat, which offers a whole range of functionalities beyond live chat, in particular for integration and campaigns, and is very cheap.

**Comment by timvines19** [comment]
Intercom also has Product Tours, which sequentially highlights different buttons/functions on a page and tells users what to do with them. I think one of those for the main UI would be really valuable. They've given us a good deal for the time being ($50 per month), so let's see how we get on. Wasn't it you that recommended Intercom to me?

**Comment by kermitt2** [comment]
yes :) indeed the Product Tours is really nice for us, I though it would be much more expensive, so it makes sense.

**Comment by timvines19** [comment]
so I can link Intercom to GitHub to enable direct logging of issues, could you pls make me an admin for the two sites?

**Comment by kermitt2** [comment]
I've integrated github dataseer-web repo with intercom!
Could maybe invite @NicolasKieffer to the intercom dataseer team too?

**Comment by timvines19** [comment]
I don't have his email!

**Comment by timvines19** [comment]
Please pause on this - I'm having discussions with people at Stencila who have had a lot of trouble creating product tours with Intercom

**Comment by kermitt2** [comment]
Our application is much simpler and self-standing than Stencilia, I would not expect a lot of technical difficulties for this kind of tour from what I have seen before, but who knows :D

**Comment by timvines19** [comment]
OK, I've got a call with the Stencila people and will get back to you

**Comment by timvines19** [comment]
OK- let's try adding Intercom for the live chat, and UserFlow (https://getuserflow.com/) for the Product Tour

**Comment by NicolasKieffer** [comment]
Does DataSeer already have an Intercom and UserFlow account?

**Comment by timvines19** [comment]
We have an intercom account - I've added you as a user but I'll try to send that information again. I'm just getting going with the UserFlow account but will add you as a a team member asap.

**Comment by timvines19** [comment]
I've activated our UserFlow account and switched us from Intercom to Crisp. Crisp should be added into the web service user interface
