### ISSUE TITLE
SN server: use file name of uploaded file as column in My Documents

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#129]
SN really want to be able to search in ‘My documents’ by manuscript ID (e.g. NPJBC-20-123 or similar)

At the moment, that information only going to be present in the file name of the pdf. Could we add ‘file name’ as a column in My Documents and All documents on the SN server? Ideally, it would take the place of the ugly raw document ID and the MS ID would be the live link to the document in the UI.

**Comment by NicolasKieffer** [comment]
Modifications done in issue https://github.com/DataSeer/dataseer-web/issues/74
Pdf filenames were not stored before, so if document don't have it, it will display "raw document ID".
If manuscript id is set, it will display it (but not always extracted, so it will be the pdf filename in most of case i think)

Note : Priorities is "manuscript ID", or "pdf filename", or "raw document ID".

Render :

All documents
![image](https://user-images.githubusercontent.com/16922410/96427564-000b3800-11ff-11eb-8d03-b437017b8064.png)

My documents
![image](https://user-images.githubusercontent.com/16922410/96428414-06e67a80-1200-11eb-8e75-79509e5aeace.png)

**Comment by kermitt2** [comment]
Question @NicolasKieffer, if it is tied with #74 it means that the PDF display/annotation will be available (and selected by default), but this document view and UI adaptation is not ready yet. If we want to add the uploaded file names in the column without the PDF storage and display, could we envisage to grab the file name at upload time independently from storing the PDF ?

**Comment by NicolasKieffer** [comment]
@kermitt2 Yes we could.

**Comment by kermitt2** [comment]
@timvines19 it's deployed on the SN server if you'd like to test 👍
