### ISSUE TITLE
Difficult Case for PDF sentence selection

### ISSUE THREAD

**Issue by kermitt2** [DataSeer/dataseer-web#134]
https://cloud.science-miner.com/dataseer-dev/documents/5fab75249a98aa090105afea

We have non selectable body text apparently misinterpreted as part of the figure content. 
The selection of sentence is not good too - possibly due to a problem of sentence segmentation and/or coordinates management.

**Comment by NicolasKieffer** [comment]
This case (small line spacing) is fixed in 95c9d21fac52010cb1b072e3a44f1f2edb01f838.
I'm working on large line spacing handling too.

**Comment by timvines19** [comment]
Has this been deployed to the dev server yet? There's some strange sentence selection issues in this pdf too: https://cloud.science-miner.com/dataseer-dev/documents/5fd1af63c745b80a8b1e3a18

- some sentences are individual words
- the paragraphs underneath are not selectable either

![Screen Shot 2020-12-09 at 9 10 44 PM](https://user-images.githubusercontent.com/49563305/101728521-624c2080-3a6b-11eb-9434-f0d2a48adfdd.png)

**Comment by kermitt2** [comment]
This issue with the initial document is directed to GROBID structuring and the impact on sentence coordinates and non selectable sentences - it was not on line spacing. Nothing has been done to address this for the moment. The second document seems having very similar problem. Likely to be fixed with addition of Grobid training data and better figure extraction.
