### ISSUE TITLE
Dataset disappears from top bar & sentence boxes too big

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#135]
This document has five datasets but once I deleted Dataset 4 it looks like Dataset 5 has disappeared from the top bar.

The boxes around the sentences are mostly just rectangles and often include surrounding sentences. The boxes seem to fit the sentence more closely in previous iterations.

https://cloud.science-miner.com/dataseer-dev/documents/5faeda189a98aa090105b2fe

![Screen Shot 2020-11-13 at 11 16 31 AM](https://user-images.githubusercontent.com/49563305/99111903-bc0f1700-25a1-11eb-91c4-f41efc7a199d.png)

![Screen Shot 2020-11-13 at 11 12 05 AM](https://user-images.githubusercontent.com/49563305/99111699-718d9a80-25a1-11eb-8825-2c12fbd8e591.png)

**Comment by NicolasKieffer** [comment]
Thoses bugs have been already patched (95c9d21fac52010cb1b072e3a44f1f2edb01f838, b90f72c6dda13c19275edee7dd3d77bd7911fe9c).
Updates will be available on Monday.
