### ISSUE TITLE
problem processing an article 

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#136]
The attached article seems to load correctly (the metadata appears), but there's an error on the document screen.

![Screen Shot 2020-11-26 at 9 02 59 PM](https://user-images.githubusercontent.com/49563305/100402732-dc16ef80-3011-11eb-979f-daa87bee742e.png)

[For dataseer.pdf](https://github.com/DataSeer/dataseer-web/files/5605585/For.dataseer.pdf)

**Comment by NicolasKieffer** [comment]
This bug happen when document don't have dataset (fixed now).
Render (different messages can be modified) :
![image](https://user-images.githubusercontent.com/16922410/100475196-c6252f80-30e2-11eb-89ee-f6364fb0d61a.png)

**Comment by timvines19** [comment]
OK, thanks. Please change the top to 'DataSeer has not detected any datasets in this document'

**Comment by timvines19** [comment]
Is this fix just on the dev server?

**Comment by NicolasKieffer** [comment]
You must re-upload the document because some data are "missing" (this case was not handled until now).
If a lot of documents are affected, I will look for a fix.

**Comment by timvines19** [comment]
Just tried loading this one again onto the dev server and it's stuck at the rotating wheel

**Comment by NicolasKieffer** [comment]
@kermitt2 It seems dataseer-dev is not up-to-date (dataser-web switched on master, node server re-installed and restarted).

**Comment by kermitt2** [comment]
Yes this one was not updated ! 

I updated dataseer-web, normally dataseer-ml is already good. fyi it's actually dataseer-ml which can really take time to update, because there are some native libraries to recompile for the Deep Learning part, depending on the version of python.

**Comment by kermitt2** [comment]
It was updated on the dev server for test and validation, so not on master yet.

**Comment by timvines19** [comment]
Looks good - please deploy to the Prod server when you can.

**Comment by timvines19** [comment]
Please also change the message from "There is no datasets in this document" to
"There are no datasets in this document"

**Comment by NicolasKieffer** [comment]
It should be displayed like this (it is currently available on dev branch).

![image](https://user-images.githubusercontent.com/16922410/103809848-73805100-505a-11eb-9032-1c533de8d3f6.png)

**Comment by timvines19** [comment]
OK, great. When will the next update for the UI take place?

**Comment by timvines19** [comment]
issue has been addressed

**Comment by timvines19** [comment]
issue has been addressed
