### ISSUE TITLE
Tabular data 'best data format for sharing' advice is truncated

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#140]
For some reason the 'Best data format for sharing' for Tabular data stops mid-sentence:

Best data format for sharing:
Tabular data should saved as a .txt or .csv file. The first row(s) should contain information about the dataset, such as the data file name, author, today's date, when the

Good example is: https://app.dataseer.ai/dataseer/documents/5fc3dbd0e73699474a3b9e82
but the problem appears on all three servers

The whole paragraph is:

Best practice for sharing this type of data:
Tabular data should be saved as a .txt or .csv file. The first row(s) should contain information about the dataset, such as the data file name, author, today's date, when the data within the file were last modified, and companion file names. Please also state which symbol has been used to denote missing data (NA is preferred). Column headings should describe the content of each column and contain only numbers, letters, and underscores - no spaces or special characters. Lowercase letters are preferred. Row names should be consistent with those used in the article and in other related datasets. You can check the formatting of tables with goodtables.io.

I've tried to 'Refresh Data types' on the Production server, but that button still only appears on older articles that only have the xml display. It's possible that the issue will be fixed by forcing a data type refresh on each server.

![Screen Shot 2020-11-29 at 9 46 17 AM](https://user-images.githubusercontent.com/49563305/100549570-7fd9e880-3228-11eb-8bb0-224969e0d318.png)

**Comment by NicolasKieffer** [comment]
@kermitt2 Bug seems to be on the dataseer-ml service side ([dev](https://cloud.science-miner.com/dataseer-ml/service/jsonDataTypes) or [prod](https://cloud.science-miner.com/dataseer-ml-dev/service/jsonDataTypes))

![image](https://user-images.githubusercontent.com/16922410/100655602-cffd9b80-334b-11eb-8510-871ac9a27c34.png)

**Comment by kermitt2** [comment]
The problem comes from the default `DataTypes.json` description file that is served by dataseer-ml and originally from the `csv` file from which the json file has been converted (there was a end-of-line at this position).

This is fixed with https://github.com/DataSeer/dataseer-ml/commit/30c499b20a4f54be7bcb936e1ac476bccd618948.

**Comment by timvines19** [comment]
the wiki has moved to https://wiki.dataseer.ai/doku.php (not .io) so the app may need to be updated. Refreshing data types left many of them blank.

**Comment by NicolasKieffer** [comment]
Fixed (available on dataseer-dev).

![image](https://user-images.githubusercontent.com/16922410/110729168-7d6f2d80-821e-11eb-853e-3090671fe91e.png)

![image](https://user-images.githubusercontent.com/16922410/110729293-bc9d7e80-821e-11eb-9c19-afb0e1098a0e.png)

**Comment by NicolasKieffer** [comment]
@timvines19 
A patch as been deployed on dataseer-dev server.
To be correctly parsed, all datatypes "title of their own page" must be be like: **Datatype- Subtype**

_Genetic Data ([url](https://wiki.dataseer.ai/doku.php?id=data_type:genetic_data))_
_Genetic Data- Amplified Fragment Length Polymorphism Analysis ([url](https://wiki.dataseer.ai/doku.php?id=data_type:genetic_data:amplified_fragment_length_polymorphism_analysis))_

I will update title of not well parsed datatypes.

**Comment by timvines19** [comment]
@samanthablankers will tackle the Datatype- Subtype issue

**Comment by samanthablankers** [comment]
Yes all done!

Sam

On Mar 17, 2021, at 6:01 PM, timvines19 ***@***.***> wrote:

﻿

@samanthablankers<https://github.com/samanthablankers> will tackle the Datatype- Subtype issue
