### ISSUE TITLE
author display in metadata not quite right

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#145]
In this article: https://app.dataseer.ai/dataseer/documents/5fd3225ae73699474a3ba233

the list of authors doesn't give an affiliation for Angela Ferguson, and the remaining 12 authors are missed

![Screen Shot 2020-12-10 at 11 53 02 PM](https://user-images.githubusercontent.com/49563305/101877432-da394a00-3b42-11eb-88f9-68ba86372619.png)

[2020.12.10.419044v1.full.pdf](https://github.com/DataSeer/dataseer-web/files/5677738/2020.12.10.419044v1.full.pdf)

The spelling of 'Submitting' also needs to be corrected

**Comment by timvines19** [comment]
the same article also has trouble on the 'finish' page:

![Screen Shot 2020-12-11 at 6 49 49 AM](https://user-images.githubusercontent.com/49563305/101917557-3a4ce200-3b7d-11eb-8ef2-9cc5919b8888.png)

**Comment by NicolasKieffer** [comment]
I have fixed this bug https://github.com/DataSeer/dataseer-web/issues/145#issuecomment-743236407

List of authors should have scroll-bar (like below)
![image](https://user-images.githubusercontent.com/16922410/102268471-ab90ea00-3f1b-11eb-968d-00d80c8a781c.png)
