### ISSUE TITLE
RepoRecommender in dataseer-web app

### ISSUE THREAD

**Issue by NicolasKieffer** [DataSeer/dataseer-web#148]
Integrate RepoRecommender in dataseer-web app as webservice

**Comment by timvines19** [comment]
Would be great to get this completed. The main problem here is getting the additional fields for reporecommender from the document. These are the subject areas, taxon, journal/publisher, institution, and funder. 

The last three should often be accessible through the document metadata (and if they're not, just leave them as 'none of these options'). Getting the subject area and taxon is harder without some Named Entity Recognition or article classification.

Another option is starting with a button in the 'recommended repositories' section saying 'Activate' – when that is clicked a window with the subject area, taxon, journal, funder, institution, drop-down menus appears and the author can enter their choices (these are prefilled if possible).

NB we've seen ASAP articles where they work with three different taxa in the same article (e.g. worms, mice and people) so we'll somehow need to take this into account
