### ISSUE TITLE
'Error processing document' for F1000 article

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#150]
This one: https://app.dataseer.ai/dataseer/documents/5fc8c2a8e73699474a3b9ff8

I think this error appears because the ML couldn't find any datasets – could the name of the error be changed to 'no datasets found' or similar? It currently seems like the UI has gone wrong

![Screen Shot 2020-12-31 at 11 29 14 AM](https://user-images.githubusercontent.com/49563305/103425459-4833c880-4b67-11eb-96cc-245f4b0dae68.png)

**Comment by samanthablankers** [comment]
![Screen Shot 2021-01-04 at 6 49 33 PM](https://user-images.githubusercontent.com/72994526/103660712-ed6de880-4f3b-11eb-806d-c25a3658bce5.png)

To follow this, once I hit "OK" to manually add datasets it doesn't appear that there are any tools available to do so.
