### ISSUE TITLE
Create API documentation for DataSeer Web service

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#166]
should be similar to the GROBID API docs: https://grobid.readthedocs.io/en/latest/Grobid-service/#grobid-web-services

We need this for integration with Research Square and Editorial Manager so it's a high priority.

**Comment by NicolasKieffer** [comment]
New doc available [here](https://github.com/DataSeer/dataseer-web/blob/fix-165/README.md) (until merge)

**Comment by timvines19** [comment]
OK, thanks for putting that together
