### ISSUE TITLE
Authors names on Loading Page

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#228]
![author list issue](https://user-images.githubusercontent.com/81999469/113795078-e011f700-9700-11eb-94f9-abb50aef1ee8.png)

The authors are not listed correctly on some articles, probably due to titles or other characters or symbols:
©kamshad Raiszadeh
Shahidi Originally

**Comment by NicolasKieffer** [comment]
Authors are extracted form [Grobid TEI file](https://app.dataseer.ai/dataseer/api/documents/606d012a79a4fd58af1a57bb/tei/content) then displayed (without post-processing data).
![image](https://user-images.githubusercontent.com/16922410/113899995-a529c500-97cd-11eb-8df2-4d38262b68d8.png)

**Comment by kermitt2** [comment]
Hello ! 

On the dev server (which I suggest to use for testing), it looks good

![Screen Shot 2021-04-08 at 02 12 17 ](https://user-images.githubusercontent.com/2340795/113949595-ef339a80-980f-11eb-9895-4d605d6a7494.png)

It seems I should update the production server !

**Comment by kermitt2** [comment]
You can fine the metadata produced by grobid/dataseer-ml for this document here -> https://cloud.science-miner.com/dataseer-dev/api/documents/606e481783a3c93ce93c58b7/tei/content

**Comment by kermitt2** [comment]
OK dataseer-ml updated on the production server too! The latest version (which was running on the dev server since a few weeks) uses the new Grobid release, which explains the quality gain when a DOI lookup is successful as here.

**Comment by Souad314** [comment]
It looks good, thank you so much.
