### ISSUE TITLE
Dataset validation page very slow to load

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#238]
For me it took 54s to display the 'Dataset Validation' page for this ms: https://app.dataseer.ai/dataseer/documents/606b51e479a4fd58af1a5776/datasets

**Comment by NicolasKieffer** [comment]
It depends a lot on the bandwidth, the technical characteristics of the client's machine (and a little bit on the server). I added more information on each step of loading the GUI.
Is it possible to have information on the stages which cause problems?

Note: I have maximum loading time of 15 seconds on my PC.

**Comment by timvines19** [comment]
loading times are significantly better
