### ISSUE TITLE
'Sign Up' doesn't work

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#258]
the g-Recaptcha isn't working on user sign up

I need to give accounts to some people today so this issue is urgent.

![Screen Shot 2021-04-13 at 11 56 32 AM](https://user-images.githubusercontent.com/49563305/114605788-4c37b200-9c4f-11eb-81d1-5b6c742a12d5.png)

**Comment by NicolasKieffer** [comment]
Automatic close, I reopen it

**Comment by NicolasKieffer** [comment]
@timvines19 It should be fixed.

_Note: "sign up" page need to be refreshed to work properly_

**Comment by timvines19** [comment]
Thanks, it's working now.
