### ISSUE TITLE
The dataset page of the UI is too slow to load the pdf

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#270]
Downloading the pdf of this article from the website takes 3 seconds:

https://www.journals.uchicago.edu/doi/pdf/10.1086/714079

Opening the same pdf on the datasets validation page of the UI takes over 40 seconds: 

https://app.dataseer.ai/dataseer/documents/6076f672fe13c63fea4127d2/metadata

How can we fix this? If we need to spend much more money on hosting then we should.

**Comment by kermitt2** [comment]
The hosting is not involved, it's displaying the PDF on the local browser which takes time. 

When opening on the UI, I have 3 seconds for the download of the PDF and 21 seconds for "displaying" the 84 pages of the PDF on my old mac book pro (late 2011) with Chrome. 

@NicolasKieffer  When opening the PDF locally from the file in Chrome, it takes around 10 seconds to render the 84 pages. Maybe something could be done to speed-up the display of pages or to display the pages in background?

**Comment by NicolasKieffer** [comment]
Yes, I will be working on improving the PDF rendering.

**Comment by timvines19** [comment]
I'm still not clear on the source of the time difference between opening the pdf in my browser (~3 seconds) and displaying the pdf in the DataSeer UI (>30 seconds). It can't be the fault of my laptop or my internet connection or anything local, because the pdf loads so quickly.

Could we somehow preload the datasets validation page behind the scenes when the user is on the metadata validation or the finish page?

**Comment by NicolasKieffer** [comment]
When you open the PDF in your browser (not in DataSeer UI), it will "only" display the background (an image per pages) & the selectable text ("chunks" of text). This workflow is handled by "pdf.js" library (that is optimized to do this job).

In the DataSeer UI, there is another "layer" build (in addition to the previous ones) containing all sentences.

Each sentence is made up of :
- the complete text of the sentence (text chunks from PDF "text layer" put together)
- the "structure" of contours (the shape of the outline)
- the "sentence render", an image (canvas) containing the text drawed (part of the PDF "background layer") with the countour drawed.

This "layer" make sentence selection possible (which is not possible in the "basic" display of the pdf).

**The web page is blocked until the entire document is built. This point can (and will) be improved. Render could be done page per page (only when page become visible for the user for example)**

_Note : "graphic processing" can take a long time and it depend on hardware._

**Comment by timvines19** [comment]
It seems that the last few pages of the document always take the longest, and this makes sense as they have figures in them. Loading the page with dataset 1 on it would be the best way to do the streaming. Loading the pages after the last dataset in the background would also be good, as the user won't get to these for a few minutes (they'll be focused on the first few datasets initially)

**Comment by NicolasKieffer** [comment]
A new version of the "datasets UI" will be installed on the dev server tomorrow.

![image](https://user-images.githubusercontent.com/16922410/116467125-a059ad80-a86f-11eb-8c95-f0be7ee77bc1.png)

Fixes and updates :

- PDF updates:
  - PDF is now rendered page per page (no more full rendering). Only firsts pages are rendrer at the begining (from the first page to the page containing the first dataset). _The following pages are progressively rendered (just before you scroll on it)._
  - Text Layer is no more rendered (that reduce the time processing).
- Auto-save improved.
- A "bulk actions" is now available (merge & delete).
- Front-end source code (events handler, API requests) have been improved to reduce time processing and lags (& make implementation of "undo" feature simplier).

**Comment by timvines19** [comment]
wow, looks really good. My only suggestion would be to include more space around each of the dataset boxes in the top bar as it looks quite crowded (and hence visually overwhelming) right now

**Comment by NicolasKieffer** [comment]
@timvines19 

Currently, DataSeer UI render the part of the PDF from the first page to the first page containing a dataset. But if the first dataset is in the middle (or at the end) of the document, it will render half (or all) the document before user will be allowed to interact with the interface.

Could it be a good idea to render only the first page of the PDF containing a dataset (and the adjacent pages)? (then previous pages will be rendering only if user scroll to the top).

**Comment by timvines19** [comment]
I'm seeing this a lot with the ASAP articles - the methods start on page 40 (after all the high resolution figures) and go from there. 

The *perfect* solution would be to display just the first page while the initial loading is happening (it's good to know that the right document is loading), then render the interactive document on the page with the first dataset. The app would need to load the adjacent pages fairly soon after.

**Comment by timvines19** [comment]
Are we still loading every page between the first page and the page with the first dataset?

**Comment by NicolasKieffer** [comment]
> Are we still loading every page between the first page and the page with the first dataset?

Fixed now.
Dev & prod servers updated.

**Comment by timvines19** [comment]
Wow - that's so much better. Thanks for fixing this.
