### ISSUE TITLE
dev sign up/sign in

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#271]
I can't make a dev sign in, and I can't use the forgot password button either:
Forgot password: this is where I was led when I clicked the link from the Forgot password email:
![image](https://user-images.githubusercontent.com/81999469/115309269-e18be800-a120-11eb-9b61-1c865cec516b.png)

We thought maybe it was because my email was already used for curating, so I tried with this one, but the drop down menu for organization doesn't come up.
![image](https://user-images.githubusercontent.com/81999469/115309448-26b01a00-a121-11eb-8edd-838a664f36e6.png)

When you click select your organization:
![image](https://user-images.githubusercontent.com/81999469/115309493-3a5b8080-a121-11eb-85cd-badb418b7cab.png)

**Comment by NicolasKieffer** [comment]
It should work now.

Just restart the "forgot password" process (at the begining) a valid link will be in the new mail.

**Comment by Souad314** [comment]
Okay, so I have a cloud dev account, but do I need a standard user dataseer beta account as well?

When I use this URL 
https://cloud.science-miner.com/dataseer-dev/backoffice/upload
I have this text code come up when I try to upload a document
![image](https://user-images.githubusercontent.com/81999469/115476935-b88a5680-a1f7-11eb-9684-d354f770b092.png)

**Comment by NicolasKieffer** [comment]
It should be fixed.

Note: Your account on the dev server has role "standard_user". Do You want to be curator?

**Comment by Souad314** [comment]
No, this is so that I can fix the UserFlow in the Standard User role, I may need to make another dev as a curator at a later time, and a prod user too,  but I'll use different addresses. 
Thank you so much, the upload works now.

**Comment by Souad314** [comment]
Hello - this is the same issue occurring for Ben the UX guy, he can't select an organization at all when he tries to sign up as a standard user.

**Comment by Souad314** [comment]
His login is fixed, I guess it just takes longer than we thought for new user emails to show up. They likely have to close the browser and try logging in again.
