### ISSUE TITLE
Renaming Buttons

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#273]
One of the things Sonya (from ASAP) mentioned was that she kept wanting to press Finish when she was done with the dataset in particular, so can the "Save for later" button be removed and the Validate button renamed to "Save this Dataset" or "Done with this Dataset"
![image](https://user-images.githubusercontent.com/81999469/115337337-a526af00-a155-11eb-88f8-76fc9b323a9e.png)
Also the Finish button should be renamed to "Finish all Datasets" or something more specific.
![image](https://user-images.githubusercontent.com/81999469/115337282-86c0b380-a155-11eb-894f-4814e784c101.png)

**Comment by NicolasKieffer** [comment]
So the button "Done with this Dataset" should automatically validate the dataset if all the required data are present?

**Comment by timvines19** [comment]
Yes, let's try it that way. 

If they haven't entered a dataset name then the prompt "Before moving on, please provide a name for this dataset" should appear. If they haven't entered a DOI or a comment, the prompt "Please provide either a DOI for the dataset or a comment in the comment box"

**Comment by timvines19** [comment]
Can we set up an 'autosave' feature like google docs has? When the user changes the text in one of the fields it says Saving... for a second or two then says 'All changes saved'. That would eliminate the need for a 'Save' feature

**Comment by NicolasKieffer** [comment]
Ok so the dataset will be "auto-saved" when user:
- write in an input (at most once every 2 seconds)
- leave an input (or stop writing in it more than 2 seconds)
- switches to another dataset

When the prompt should appear? Should I remove the "Done with this Dataset" button?

**Comment by timvines19** [comment]
I think we should have the autosave as you describe above, and just one 'Done with this Dataset' button, which validates it (doing the checks above) and moves on to the next dataset

**Comment by timvines19** [comment]
Thanks - looks better. Could you please put 'Done with this Dataset' in the same font as the other buttons? Could you also change 'Metadata' to 'Back to Metadata'

**Comment by timvines19** [comment]
Looks good, please deploy to Production
