### ISSUE TITLE
Bulk Actions for Datasets

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#274]
![image](https://user-images.githubusercontent.com/81999469/115337776-7826cc00-a156-11eb-9596-72e53b3346f2.png)

Building on more feedback from ASAP, 
Can there be bulk actions: 

- merge -- take second data sentence, delete existing dataset, link sentence to first data sentence
- delete
- note -- highlight specific datasets flagged by curators/annotators for author's attention
Of course authors can still look at all datasets, but to highlight an issue with the data type or sharing ability would be so much easier.

**Comment by timvines19** [comment]
this has been implemented
