### ISSUE TITLE
Renaming Datasets

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#275]
Once someone enters any text here
![image](https://user-images.githubusercontent.com/81999469/115338674-2d0db880-a158-11eb-8eba-292f705935d2.png)

It should show up here once they click out of the text box or even once they save the dataset
![image](https://user-images.githubusercontent.com/81999469/115338711-444ca600-a158-11eb-9d70-4beab4375b96.png)

**Comment by NicolasKieffer** [comment]
Feature available on Production & Developpment  server.

**Comment by Souad314** [comment]
Wow!! That's so neat! Thank you so much.

**Comment by timvines19** [comment]
@NicolasKieffer could you make the margins on either side of the dataset name a little bigger?

![Screen Shot 2021-04-20 at 4 52 37 PM](https://user-images.githubusercontent.com/49563305/115478014-07d18680-a1fa-11eb-9b3c-7f7806670145.png)

**Comment by NicolasKieffer** [comment]
Done on Production & Developpment server.
