### ISSUE TITLE
Grobid detection issue

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#296]
![image](https://user-images.githubusercontent.com/81999469/116475520-d0349100-a82e-11eb-8fe9-8197b9c2720c.png)

DataSeer found some of the correct data sentences, but missed data sentences that are functionally the same but referring to different data collection.
So, MxF pond Data was AI found, but MxF lab Data had to be added manually.
It also originally had the linked sentences in MxF Pond Data as separate datasets.

Tim suggested maybe Grobid is delimiting the methods section too soon?

**Comment by kermitt2** [comment]
Thanks @Souad314 ! could you link the actual document to the issue?

**Comment by Souad314** [comment]
Yes of course, here's the URL
https://app.dataseer.ai/dataseer/documents/60886f6e6a24cc3c8cb3bb27/datasets

and what copied when I pressed the chain 
![image](https://user-images.githubusercontent.com/81999469/116481344-da0ec200-a837-11eb-8cbd-2d76c7e1b1e7.png)

https://app.dataseer.ai/dataseer/documents/60886f6e6a24cc3c8cb3bb27?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjA4ODZmNmU2YTI0Y2MzYzhjYjNiYjI3IiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjE5NTU0MTgyLCJleHAiOjE2MjIxNDYxODJ9.WOCX-1UJPGWhGSrVxt5-K3ZA9ErEuw827CHMhFxvRNY

**Comment by Souad314** [comment]
Yikes! I'm so sorry!
https://app.dataseer.ai/dataseer/documents/60886f6e6a24cc3c8cb3bb27/datasets

**Comment by NicolasKieffer** [comment]
@kermitt2 @Souad314
There is no problem sharing the public URL of a document.
This kind of URL (with a **documenToken**) only gives "standard_user" rights on the document (access/modification).

Note: It only allows the user to access the "modification part" of the document (metadata, process, finish) of dataseer-web.

**Comment by timvines19** [comment]
@NicolasKieffer is your response more about https://github.com/DataSeer/dataseer-web/issues/272#issue-862020859?

**Comment by Souad314** [comment]
I had commented an APL from my curator account without thinking yesterday (immediately deleted) and was asking if sharing the URL is as bad
