### ISSUE TITLE
Text Selecting Bug

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#299]
![image](https://user-images.githubusercontent.com/81999469/116480225-cb271000-a835-11eb-98f9-a6d1042e9cd5.png)
"set" is the dataset selected here, it is also impossible to select any text after "set" until the footnote.
![image](https://user-images.githubusercontent.com/81999469/116480331-fe699f00-a835-11eb-99c8-f47015ecb08e.png)

Note that this article was somehow uploaded on the dev server: 
https://cloud.science-miner.com/dataseer-dev/documents/60851b085f72f75fb95eaabb/datasets

But this does happen sometimes:
- in math-heavy articles that use symbols such as theta or sigma
- in articles that have a lot of text under the figures
- in Ken's article that has a PREPRINT watermark

**Comment by kermitt2** [comment]
For the wrong data sentence box and non-selectable text, this is the same as #301 

The "fulltext" view gives the expected TEI content and selection:

![Screenshot from 2021-04-29 03-15-13](https://user-images.githubusercontent.com/2340795/116491065-4a016480-a899-11eb-94e0-60991b54dfe7.png)

so this is likely a PDF box rendering issue. 

Corresponding content in the TEI:

```xml
                <p>
                    <s coords="3,72.00,558.95,162.68,9.81">OSCAR 
                        <ref target="#b34" type="bibr">(Ortiz Suárez et al., 2019</ref>) is a set of monolingual corpora extracted from Common Crawl snapshots, specifically from the plain text WET format distributed by Common Crawl which removes all the HTML tags and converts the text formatting to UTF-8.
                    </s>
                    <s coords="3,238.12,558.95,25.45,9.81">It is deduplicated and follows the same approach as 
                        <ref target="#b21" type="bibr">Grave et al. (2018)</ref> by using FastText LangID 
                        <ref target="#b24" type="bibr">(Joulin et al., 2016</ref>
                        <ref target="#b25" type="bibr">(Joulin et al., , 2017</ref> on a line-level.
                    </s>
                    <s coords="3,274.48,559.37,15.79,9.46">No other filtering was applied.</s>
                    <s cert="0.27852341532707214" coords="3,72.00,572.92,12.36,9.46" id="dataset-6" reuse="true" type="tabular data">For five languages (bg, ca, da, fi, id) OSCAR corpora were used to train ELMo 
                        <ref target="#b35" type="bibr">(Peters et al., 2018)</ref> embeddings for POS tagging and dependency parsing, outperforming Wikipedia-sourced embeddings (Ortiz 
                        <ref target="#b33" type="bibr">Suárez et al., 2020)</ref>.
                    </s>
                </p>
```

also note that there is no sentence segmentation error here, so it should not be the problem.

**Comment by kermitt2** [comment]
Otherwise dataseer in general is trained for biomedicine. The dataset recognition will not work in this math and info domains, because the wording and data usage/sharing practices are very different. We will need to extend the training data to cover this domain.

**Comment by NicolasKieffer** [comment]
It could come from my "chunk data" extraction process.

**Comment by Souad314** [comment]
So I'm working on this document and some of the text isn't available at all

The pdf has this:
![image](https://user-images.githubusercontent.com/81999469/116613875-0edd5080-a8ee-11eb-9b6b-3a7312a0f85f.png)


DataSeer's view of the same part:
![image](https://user-images.githubusercontent.com/81999469/116614198-77c4c880-a8ee-11eb-826a-0bcacec1d1d8.png)


https://app.dataseer.ai/dataseer/documents/6089694d6a24cc3c8cb3bb49/datasets

I'm not sure if this belongs here or in another issue.

**Comment by kermitt2** [comment]
The PDF looks correct in dataseer https://app.dataseer.ai/dataseer/api/documents/6089694d6a24cc3c8cb3bb49/pdf/content ... it's the one rendered.

The text can be selected in this area: 
![Screen Shot 2021-04-30 at 00 11 41 ](https://user-images.githubusercontent.com/2340795/116624704-ae2f3180-a948-11eb-88e5-38d55e81f7f5.png)

Are you comparing different versions/PDF of the articles maybe ?

**Comment by Souad314** [comment]
The part that's missing in DataSeer is the Supplemental Material and Methods directly after the equation. 
I'm unsure what version was uploaded because it's one of the ones from Sonya from ASAP. 
When I go into the document to validate, at the Metadata stage I take the doi and find the article in another window so that I can follow any links or select text if it has Greek symbols to name Datasets correctly. I just noticed this text is missing from all views on DataSeer.

**Comment by kermitt2** [comment]
> The part that's missing in DataSeer is the Supplemental Material and Methods directly after the equation.

mmm apparently the part missing is not present in the PDF loaded on dataseer -> https://app.dataseer.ai/dataseer/api/documents/6089694d6a24cc3c8cb3bb49/pdf/content 
so Dataseer is doing its job correctly. 

The version pointed by the DOI https://doi.org/10.1101/2020.10.07.328906 looks the same as the one loaded: 
https://www.biorxiv.org/content/10.1101/2020.10.07.328906v2.full.pdf

Are you using another DOI maybe ?

**Comment by Souad314** [comment]
Okay, something went way wrong there, but it was on my end, I got version 1 from the doi from the metadata (it's a preprint)

https://www.biorxiv.org/content/10.1101/2020.10.07.328906v1.full.pdf
It even has a different title(which I missed), but it's the same abstract and first paragraph.

**Comment by Souad314** [comment]
https://app.dataseer.ai/dataseer/documents/60896a0c6a24cc3c8cb3bb69/datasets
On pdf view it seemed to select nothing
![image](https://user-images.githubusercontent.com/81999469/116637480-e880da80-a918-11eb-83fa-0e46aee09f9c.png)
In full text there's an issue with the sentence text getting cut off.
![image](https://user-images.githubusercontent.com/81999469/116637553-0fd7a780-a919-11eb-9232-1496c53c99fc.png)

Also, the first 4 datasets were in a cluster in the Results. I left that weird selection there, but we're working on these ones today.
