### ISSUE TITLE
Enter Message ... should be specific to current dataset

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#302]
When I type a message in the space for the user to see, the same message autofills into that space for all other datasets:
Dataset 2
![image](https://user-images.githubusercontent.com/81999469/116622082-f6befe80-a8f8-11eb-890d-a54a955f9c11.png)
I typed "This is a message" then found another dataset, Dataset 3 was added:
![image](https://user-images.githubusercontent.com/81999469/116622248-3f76b780-a8f9-11eb-9b52-a1af8eb9cbab.png)

The message is likely specific to that data sentence and may not apply to all datasets.

**Comment by Souad314** [comment]
This is still happening, but it doesn't save the name of the dataset
https://www.loom.com/share/75938deef1f34deea0c56096b8156ce6

**Comment by NicolasKieffer** [comment]
Should be fixed now.

Available in dev & prod servers
