### ISSUE TITLE
Most suitable repositories 

### ISSUE THREAD

**Issue by samanthablankers** [DataSeer/dataseer-web#306]
Hello, 

Under Most Suitable Repositories, all data types are presenting "Not applicable" even after refreshing the datatypes although this does not match the wiki 

Thanks, 
Sam

**Comment by NicolasKieffer** [comment]
Because it's not handled yet on the production server (but it will be soon, it work already on the dev server).

**Comment by NicolasKieffer** [comment]
My bad, there was a bug ... Fixed now.
