### ISSUE TITLE
reorder datasets according to where they appear in the article

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#314]
Adding a new dataset puts it at the end of the list, even if it's the first dataset in the article. 

It would be much more intuitive if the dataset list in the top bar matched their order in the manuscript (based on the location of the first sentence, for datasets with more than one linked sentence)

**Comment by timvines19** [comment]
is this deployed on production?

**Comment by NicolasKieffer** [comment]
Issue auto-close by commit sorry.

Yes it should be available on [prod server](https://app.dataseer.ai/dataseer).

**Comment by timvines19** [comment]
they're still in the old order on this one:

https://app.dataseer.ai/dataseer/documents/6089690e6a24cc3c8cb3bb3d/datasets

**Comment by NicolasKieffer** [comment]
Ok, that's because I use the order of appearance of sentences in the XML (that in some cases is not be the same as in PDF)... I will fix it.

**Comment by NicolasKieffer** [comment]
Notes (only for the PDF):
For the moment, with the current structure of data, I can only sort datasets (& sentences) "per page". In some cases, datasets (& sentences) in the same page can be unsorted. I will improve it in incomming days.

**Comment by timvines19** [comment]
Did you make these improvements?

**Comment by NicolasKieffer** [comment]
Not yet, I will look at this today.

**Comment by timvines19** [comment]
the datasets in this article are still in the wrong order:

https://app.dataseer.ai/dataseer/documents/606b91c979a4fd58af1a5794/datasets

**Comment by NicolasKieffer** [comment]
Updated on dev & production server.

**Comment by Souad314** [comment]
This should be reflected on the Finish page in both the Suggested Availability Statement and the order of the datasets

https://www.loom.com/share/f0201643f507448fa7f5857afe9997c6
