### ISSUE TITLE
autosave removes text while typing

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#317]
The autosave should probably kick in when the user moves the cursor out of the active text box, as currently the autosave kicks in every 2 seconds and makes it hard to type (letters keep disappearing). It's most visible in the video below when I'm typing "tryin" in the comments to user 

https://www.loom.com/share/7a4a2e1901824472a9a4cef2ece9c8b2

**Comment by NicolasKieffer** [comment]
I will update it to not "slow down" the save rate.

_Note : Auto save is "throw" when user stop typing after 750ms, not "every X secondes" (but 750ms after a "typing sequence")._

![image](https://user-images.githubusercontent.com/16922410/116792023-8feb4200-aabe-11eb-80cb-ecaea411a1dd.png)

**Comment by NicolasKieffer** [comment]
Fixed: Data are now saved 2 seconds after the end of a "typing sequence", and/or when user leave an input.

**Comment by timvines19** [comment]
this is much better now
