### ISSUE TITLE
Add a link to the actual pdf in the top bar (visible for all users) 

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#320]
Would be great to be able to open the actual pdf in a separate screen to allow us to search for specific text or copy/paste DOIs of shared datasets into the UI. Maybe here:

![show pdf button](https://user-images.githubusercontent.com/49563305/116792159-d2d3f800-aa73-11eb-984b-d37718923a8f.png)

**Comment by NicolasKieffer** [comment]
auto closed so I reopen it

**Comment by timvines19** [comment]
this has been completed
