### ISSUE TITLE
Deleting dataset removes other datasets

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#329]
trying to delete the 'Bulk tissue eQTL' dataset deletes the other datasets

https://app.dataseer.ai/dataseer/documents/608969e56a24cc3c8cb3bb63/datasets

https://www.loom.com/share/074a4632c7a540cabfac89d4e54c0a2b

**Comment by NicolasKieffer** [comment]
My bad. Should be fixed now (both on dev & prod)

**Comment by timvines19** [comment]
seems to be fixed - thanks very much
