### ISSUE TITLE
Data Sentences Missing on Finished Page

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#339]
The data sentences are not showing up on the Finish page for the later numbered datasets in more than one article
![image](https://user-images.githubusercontent.com/81999469/117201912-0e3b3300-ada2-11eb-8ed5-b7f5d19e2c1b.png)

**Comment by NicolasKieffer** [comment]
Should be fixed (both prod & dev servers).

There is a button "refresh datasets" on the "finish" page to correct the datasets informations.

![image](https://user-images.githubusercontent.com/16922410/117307646-07372200-ae81-11eb-9cda-fadc70a16d64.png)

**Comment by NicolasKieffer** [comment]
Fixed now.

Only available for curators.

Updated on dev & prod server.

**Comment by Souad314** [comment]
![image](https://user-images.githubusercontent.com/81999469/119555141-5ff82d00-bd52-11eb-8ec8-83d337599fb1.png)
[public url](https://app.dataseer.ai/dataseer/documents/608969986a24cc3c8cb3bb51?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjA4OTY5OTg2YTI0Y2MzYzhjYjNiYjUxIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjE5NjE4MjY4LCJleHAiOjE2MjIyMTAyNjh9.2gWJaDoOtjSjM7Ng7Qz6R2rlInPKY7S_H4CEJjubA30)
