### ISSUE TITLE
Re-order Datatype output on Finish Page

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#340]
The desired order for each dataset output:
Dataset #
Dataset Name
Data Type
Data Sentence
Stable Identifier
Comments

![image](https://user-images.githubusercontent.com/81999469/117212471-3ed59980-adaf-11eb-9f7f-c159cee753e9.png)

Each line needs to be present regardless if there's text in the textbox at the processing stage, perhaps these messages could display if there is no text in the box?
Stable Identifier: ![image](https://user-images.githubusercontent.com/81999469/117212638-72b0bf00-adaf-11eb-8219-a183eec789e3.png)
Comments: ![image](https://user-images.githubusercontent.com/81999469/117212700-865c2580-adaf-11eb-8361-3ddc07f9f034.png)

**Comment by NicolasKieffer** [comment]
@Souad314 

Would this kind of ouput be correct?

Example : https://cloud.science-miner.com/dataseer-dev/documents/609188a0d1c7b5657258e9cd/finish

Note: it's only available on the [dev server](https://cloud.science-miner.com/dataseer-dev/) for the moment.

**Comment by Souad314** [comment]
Oh yes, that's exactly it, thank you!

Just to clarify - 
![image](https://user-images.githubusercontent.com/81999469/117329186-3df14600-ae49-11eb-8267-07e516d775e7.png)
Does this info change when text is put into the name and doi box?
Would it be possible to have it default to 
Dataset id: Dataset name: doi ?

**Comment by NicolasKieffer** [comment]
If the dataset name is set, the dataset id will not be shown. I will be replaced by the dataset name.
The dataset id is shown to inform the user which one "cause problems" (so user can identify it in the "dataset" section for example).

**Comment by timvines19** [comment]
My feeling is that it should be under the metadata, not above it. I also don't think it should be in a window with a slide bar – I'd prefer it to just be plain text that the authors can grab and paste into their document. Even if there's 20 datasets this section won't be all that long

**Comment by NicolasKieffer** [comment]
Ok I will update it.

**Comment by Souad314** [comment]
I think the Dataset ID should match the Dataset Number, or don't have the Dataset ID in there at all.
![image](https://user-images.githubusercontent.com/81999469/118846209-56b61e80-b881-11eb-88d5-49a20714b066.png)

**Comment by Souad314** [comment]
This is also very text-heavy:
![image](https://user-images.githubusercontent.com/81999469/118846967-1905c580-b882-11eb-8f69-91d70b55374b.png)

Before this update, no information would show up here UNLESS there was text in the doi or comment box. That's why Sam and I would put an X or . in those text boxes.
The summary of Datatype Names should show up, but if an article like this one initially doesn't have any doi or comment, it's very hard to read it.
Is there any way to have just this, but where I don't have to go back and put . in every doi box?
![image](https://user-images.githubusercontent.com/81999469/118848103-4acb5c00-b883-11eb-934e-577787055727.png)

**Comment by NicolasKieffer** [comment]
https://github.com/DataSeer/dataseer-web/issues/340#issuecomment-844260916

The dataset id is used to identify the dataset in the application. (It will be hidden)
I will replace it by the "dataset number".

https://github.com/DataSeer/dataseer-web/issues/340#issuecomment-844261681

Yes, I will replace the "empty" value by a dot (or another char/text)

**Comment by NicolasKieffer** [comment]
Dev & Prod servers updated
