### ISSUE TITLE
Control Click and Shift Click function to select multiple sentences

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#352]
Would it be possible to add this function on the Processing page?
It seems intuitive to want to use these functions while processing.

**Comment by NicolasKieffer** [comment]
Should be available now (in dev & prod servers).

Note: I have to improve the sentences sorting on the PDF view but it do not concern this feature (c.f. [this one](https://github.com/DataSeer/dataseer-web/issues/314))

**Comment by NicolasKieffer** [comment]
Sentence sorting fixed now (c.f. https://github.com/DataSeer/dataseer-web/issues/314#issuecomment-845087257)
