### ISSUE TITLE
The public link should not be modifiable/no changes saved without signing in

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#361]
https://www.loom.com/share/01e613cbecb04507af805fc0fe263288

![image](https://user-images.githubusercontent.com/81999469/118372921-d03fcb00-b568-11eb-905e-52e158800f6c.png)
Also, it doesn't show in the Modified by column in the All Documents page that someone not signed in has done anything - probably because there's no email attached to the not signed in path?
I also tried this in the Dataset Name text box by deleting the title (it reverts back to dataset-2) and changing the name of it as well. I deleted the dataset and added one without issue, it was saved.
This whole side should be visible, but no buttons, no adding or deleting datasets, nothing should be changeable or no changes are saved unless the user is signed in.

https://app.dataseer.ai/dataseer/documents/606b90b979a4fd58af1a578c/datasets

[public url](https://app.dataseer.ai/dataseer/documents/606b90b979a4fd58af1a578c?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjA2YjkwYjk3OWE0ZmQ1OGFmMWE1NzhjIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIxMDQ5OTc5LCJleHAiOjE2MjM2NDE5Nzl9.lvNGmaPpRrVfkjeG0JswuwTooFzRcle_OkMx8ZfcBy8)

**Comment by timvines19** [comment]
I think this is functionality we actually need - if a signed in author wants a co-author to come to the UI and provide information about a dataset then we don't want the co-author to have to create an account.

**I do agree that the 'Modified by' column should record that Anonymous made changes to the datasets**

**Comment by NicolasKieffer** [comment]
Should be fixed now.

Available in dev & prod servers
