### ISSUE TITLE
dataset 6 is indestructible

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#364]
The last dataset on the list has the swirling dots for auto save and can't be edited or deleted

https://app.dataseer.ai/dataseer/documents/60a063650814f3065a3d7949/datasets

https://www.loom.com/share/a469a566a7524bd6a1ea98a564e5713c

**Comment by NicolasKieffer** [comment]
It seems he is deleted now. (It could happen after an app crash or a server restart while you work on a document).

**Comment by timvines19** [comment]
seemed like an isolated bug
