### ISSUE TITLE
Bulk Actions for All Documents

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#372]
Whenever an action is performed on one doc, the parameters of the search reset.
Here's an example:
https://www.loom.com/share/e3afdc768a614cb2b3868b215ec374d3

Is there a way to perform bulk actions on the All Documents page?
For example, we need to reclassify a large number of articles as Molecular Connections, but it will be far too tedious to do them individually - especially since there's so many and they're from more than two months ago. Is there a way these docs can be handled on the back end?

**Comment by NicolasKieffer** [comment]
> Is there a way to perform bulk actions on the All Documents page?

Not for the moment. I will work on it today (keep searchparams after an update & multiple organisation affectations at once)

> For example, we need to reclassify a large number of articles as Molecular Connections, but it will be far too tedious to do them individually - especially since there's so many and they're from more than two months ago. Is there a way these docs can be handled on the back end?

I can change it directly in the database (manually) if it's urgent, else this will be possible in the backoffice soon. 

_Note: If you need another feature, so just describe it there. I will try to implement it soon as possible._

**Comment by NicolasKieffer** [comment]
The form now keeps the params after an update (on dev & prod server)

I will implement the bulk actions over the next few days.

**Comment by NicolasKieffer** [comment]
The bulk actions is implemented in dev & prod (only available for curators)
![image](https://user-images.githubusercontent.com/16922410/119361548-15bc7080-bcac-11eb-88a4-1d3fce6633e6.png)
