### ISSUE TITLE
Reclassifying Subtypes

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#392]
As was mentioned in the meeting Friday, some datatypes were recently reclassified as subtypes, would it be possible to run a command line to fix them all on the backend:

**Was:** 

- Other: Code
- None: old datatype other:code

**should now be** 
Datatype: Other
Subtype: Code

**Was:**

- Other: Protocol
- None: old datatype other:protocol

**should now be** 
Datatype: Other
Subtype: Protocol

**Was:** 

- Other: Reagent
- None: old datatype other:reagent

**should now be** 
Datatype: Other
Subtype: Reagent

Thank you so much

**Comment by NicolasKieffer** [comment]
@Souad314 
Should be fixed (on the production server)

List of all modified documents :
> "othercode" => "Other: Code"

https://app.dataseer.ai/dataseer/documents/6089690e6a24cc3c8cb3bb3d/
https://app.dataseer.ai/dataseer/documents/608969156a24cc3c8cb3bb3f/
https://app.dataseer.ai/dataseer/documents/608969956a24cc3c8cb3bb4f/
https://app.dataseer.ai/dataseer/documents/608969986a24cc3c8cb3bb51/
https://app.dataseer.ai/dataseer/documents/60a0637f0814f3065a3d794f/
https://app.dataseer.ai/dataseer/documents/60a693b1a93d4d7cd76c46f4/
https://app.dataseer.ai/dataseer/documents/60b0285101aacd5baf0a660f/

> "otherprotocol" => "Other: Protocol"

https://app.dataseer.ai/dataseer/documents/6089690e6a24cc3c8cb3bb3d/
https://app.dataseer.ai/dataseer/documents/608969156a24cc3c8cb3bb3f/
https://app.dataseer.ai/dataseer/documents/6089694d6a24cc3c8cb3bb49/
https://app.dataseer.ai/dataseer/documents/608969956a24cc3c8cb3bb4f/
https://app.dataseer.ai/dataseer/documents/608969986a24cc3c8cb3bb51/
https://app.dataseer.ai/dataseer/documents/608969e26a24cc3c8cb3bb61/
https://app.dataseer.ai/dataseer/documents/60896a0c6a24cc3c8cb3bb69/
https://app.dataseer.ai/dataseer/documents/60a693b1a93d4d7cd76c46f4/
https://app.dataseer.ai/dataseer/documents/60aea91c01aacd5baf0a65cd/
https://app.dataseer.ai/dataseer/documents/60b0285101aacd5baf0a660f/

> "otherreagent" => "Other: Reagent"

https://app.dataseer.ai/dataseer/documents/6089690e6a24cc3c8cb3bb3d/
https://app.dataseer.ai/dataseer/documents/608969156a24cc3c8cb3bb3f/
https://app.dataseer.ai/dataseer/documents/608969956a24cc3c8cb3bb4f/
https://app.dataseer.ai/dataseer/documents/608969986a24cc3c8cb3bb51/
https://app.dataseer.ai/dataseer/documents/60896a0c6a24cc3c8cb3bb69/
https://app.dataseer.ai/dataseer/documents/60b0285101aacd5baf0a660f/

@NicolasKieffer 
Commands:
```
db.documents.datasets.find({"current.dataType":"othercode"}, {"_id":1, "document": 1})
db.documents.datasets.find({"current.dataType":"otherprotocol"}, {"_id":1, "document": 1})
db.documents.datasets.find({"current.dataType":"otherreagent"}, {"_id":1, "document": 1}) 

db.documents.datasets.updateMany({"current.dataType":"othercode"}, {$set:{"current.$[elem].dataType":"other","current.$[elem].subType":"code"}}, {"multi": true, "arrayFilters": [{"elem.dataType": "othercode"}]})
db.documents.datasets.updateMany({"current.dataType":"otherprotocol"}, {$set:{"current.$[elem].dataType":"other","current.$[elem].subType":"protocol"}}, {"multi": true, "arrayFilters": [{"elem.dataType": "otherprotocol"}]})
db.documents.datasets.updateMany({"current.dataType":"otherreagent"}, {$set:{"current.$[elem].dataType":"other","current.$[elem].subType":"reagent"}}, {"multi": true, "arrayFilters": [{"elem.dataType": "otherreagent"}]})
```

**Comment by Souad314** [comment]
Thank you very much
