### ISSUE TITLE
Jumping locations in pdf when a dataset is deleted

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#396]
When a dataset is deleted, sometimes it jumps back to the first dataset, sometimes it jumps back to the last one modified. 
Sometimes the correct data sentence is the next sentence chronologically, or some near-by sentence because the English language is so silly and the way the author phrased it (rightfully) confused DS.

https://www.loom.com/share/705ec61e30d14f13b0d453b89abeef51

Is it possible to remain in the same location of the article once the dataset is deleted? Perhaps even with the dashed selection still there, in case it was a deletion by accident?
![image](https://user-images.githubusercontent.com/81999469/121085017-33063a00-c796-11eb-959d-b365eea0be50.png)

**Comment by NicolasKieffer** [comment]
The default behavior is to go to the "next dataset" (so if you delete the last one, it will go to the first).
I will remove it (for removal) in the next update.

**Comment by Souad314** [comment]
Thank you for that clarification, and thank you for replying so quickly!
