### ISSUE TITLE
Break link button appears for all new and existing datasets

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#418]
and pressing it deletes the dataset. Dataset 2 in the Loom existed before, I created Dataset 8.

https://www.loom.com/share/b647c0ffed0048faac905aa7f8038f41 

[Boet et al.](https://app.dataseer.ai/dataseer/documents/60c9fb38bd77713d13b14a75?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBjOWZiMzhiZDc3NzEzZDEzYjE0YTc1IiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIzODQ5Nzk4LCJleHAiOjE2MjY0NDE3OTh9.NCoGTp5yW1pkGvUjKpzLTBqj-xv09bHWvWVONKNkgCk)

I don't think we need the button there, there's a nice big button in the corner to delete the dataset if necessary.

**Comment by NicolasKieffer** [comment]
This button allows you to "unlink" the sentence from the dataset. If you "unlink" the last sentence then it will delete the dataset (because it do not have sentence anymore)
_That's why this button is displayed for each sentence linked to a dataset._
