### ISSUE TITLE
DS may be deleting datasets in these large quantity edge cases

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#420]
https://www.loom.com/share/211f235cbb8b46e692125f8bf4966ce2

The last datasets created in this massive (86 dataset) case get lost somehow and un-selectable. This also happened in Cai et al. and in Yoo et al. (Each with never-before-seen numbers of datasets)

Is this because of the quantity of datasets has never been done before? or is it because the documents are so large? a combination of both? 
Or is it a bug?

**Comment by NicolasKieffer** [comment]
It's a bug. This happens because the sentences are no longer "available" (not anymore in the TEI file).

_I'll try to find why, maybe due to reformatting the TEI._
