### ISSUE TITLE
Template Report Format to send to BioRxiv

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#439]
@NicolasKieffer can you provide the code to send to BioRxiv for this pop up of text to appear next to an article uploaded through b --> x:

Direct copy and paste from Hypothes.is Note:
### Data Discovery/Status Report

Click [Here](https://app.dataseer.ai/dataseer/documents/60c2995d01aacd5baf0a6891?documentToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjBjMjk5NWQwMWFhY2Q1YmFmMGE2ODkxIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjIzMzY2MDE0LCJleHAiOjE2MjU5NTgwMTR9.wr2yAu2DCGMTOiPk7iYWNmmtcCVVjqhjOkwxRm-a7gI) for the full report.

**Summary of Datasets and Open Science materials associated with article:**
- 15 Protocols
- 27 Datasets

**5 Images**
- 1 Image(s)
- 3 Microscopy images
- 1 Photograph(s)

**4 Genetic Datasets**
- 2 Sequence Alignments
- 2 High-Throughput Nucleotide Sequencing datasets

**18 Tabular Datasets**
- 15 Tabular data
- 2 Assays
- 1 Fluorometry dataset(s)

**16 Instances of Code**

**13 Lab Materials**
- 8 Reagents
- 3 Materials
- 2 Lab Resources

Screenshot of Note:

![image](https://user-images.githubusercontent.com/81999469/126203533-983706bf-9b38-4f55-84ff-c6a8ecf6f044.png)

Internal notes:

- The URL should be a link to the DS Interface version of article displayed on bioRxiv (preferably in the Finished state)
- If there's only one of something, keep the word singular. The "s" in closed parentheses is for words that receive an s if there's more than 1 (the exception is the word "data" which is already singular and plural - _special thanks to the English language for being so ridiculous_)

**Comment by timvines19** [comment]
The curator will have to enter the URL for the bioRxiv article where we send this information, as the URL won't be included in the .zip that gets sent to us from B2X
