### ISSUE TITLE
Strange sentence selection case 

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#441]
So this article has some issues with text selection, but it's doing something strange compared to the others..
The AI somehow obtained the correct sentence, even though it is not selectable.

https://www.loom.com/share/f3228ab3287342c8828474e9aa89da8c

In these cases I try to select the lowermost words in the paragraph (those closest to the actual dataset collection sentence) and then I'll often find the correct dataset sentence in the pdf and copy the correct selection into the comment box.

[Kumar et al. 2021](https://app.dataseer.ai/dataseer/documents/610877b905da56464c96c7dc?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjEwODc3YjkwNWRhNTY0NjRjOTZjN2RjIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjI3OTQ0OTE0LCJleHAiOjE2MzA1MzY5MTR9.8Lfv0mSzfyAY_GTPe33ZH7kE6LTOpP46Y0xW1Mgft-0)

[Kumar et al. 2021 pdf](https://app.dataseer.ai/dataseer/api/documents/610877b905da56464c96c7dc/pdf/content?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjEwODc3YjkwNWRhNTY0NjRjOTZjN2RjIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjI3OTQ0OTE0LCJleHAiOjE2MzA1MzY5MTR9.8Lfv0mSzfyAY_GTPe33ZH7kE6LTOpP46Y0xW1Mgft-0)

Related to [Issue 313](https://github.com/DataSeer/dataseer-web/issues/313)

**Comment by kermitt2** [comment]
It seems coming from wrong sentence coordinates on the dataseer-ml side. The generated TEI looks good, with the sentences defined as expected for all this paragraph, but the coordinates for the problematic sentences does not look good. 

```xml
            <div>
                <head>ODD-luciferase activity assaay</head>
                <p>
                    <s coords="23,54.00,240.29,504.00,11.14;23,54.00,267.89,158.47,11.14" xml:id="sentence-199">The ODD-luciferase construct with pcDNA3.1 plasmid vector was constructed as previously described 
                        <ref target="#b42" type="bibr">(Safran et al. 2006)</ref>.
                    </s>
                    <s coords="23,215.06,267.89,342.94,11.14;23,54.00,295.49,504.01,11.14;23,54.00,323.09,222.14,11.14" xml:id="sentence-200">The proline p402 and p564 present within the oxygen degradation domain (ODD) of HIF1α, when hydroxylated by HIF-PHDs, allow its binding to the VHL protein that target it for proteasomal degradation.</s>
                    <s coords="23,279.87,323.09,278.13,11.14;23,54.00,350.69,354.71,11.14" xml:id="sentence-201">In this way, the stabilization of ODD can be used as a marker of HIF1α stability 
                        <ref target="#b42" type="bibr">(Safran et al. 2006</ref>
                        <ref target="#b48" type="bibr">, Smirnova et al. 2010</ref>.
                    </s>
                    <s coords="23,408.71,350.69,11.34,11.14" xml:id="sentence-202">Because of the luciferase tagged with ODD, the increase in ODD stability leads to a proportional increase in the luciferase activity and this provides a very good way of measuring the HIF1α stability in a quantitative manner with a wide dynamic range.</s>
                    <s coords="23,423.35,350.69,46.70,11.14" xml:id="sentence-203">To this end, we used SH-SY5Y cells stably expressing ODDluciferase.</s>
                    <s coords="23,473.35,350.69,10.01,11.14" xml:id="sentence-204">These cells were made by co-transfecting ODD-luciferase plasmid along with a puromycin resistance plasmid in SH-SY5Y cells and stably transfected cells were positively selected in presence of 4μg/ml of puromycin.</s>
                    <s coords="23,486.66,350.69,71.34,11.14" xml:id="sentence-205">Luciferase activity was measured by luciferase assay kit (promega) using an LMaxII TM microplate luminometer (molecular Devices).</s>
                    <s coords="23,54.00,378.29,36.70,11.14" xml:id="sentence-206">ODDluciferase activity was normalized to the protein content of each well measured by Bio-Rad DC TM protein assay kit.</s>
                </p>
            </div>
```

**Comment by kermitt2** [comment]
After fix in Grobid https://github.com/kermitt2/grobid/pull/821, see https://github.com/kermitt2/grobid/issues/811#issuecomment-903217644, it's working fine: 

![Screen Shot 2021-09-13 at 09 07 20 ](https://user-images.githubusercontent.com/2340795/133040230-9e0a06ef-9d32-40f1-86ed-960ce0cfdc04.png)
