### ISSUE TITLE
errors in searching all documents

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#442]
I'm trying to find a doc for American Naturalist that Souad uploaded recently, but I can't . Somehow selecting only 'American Naturalist' for the Organization doesn't narrow it down to just that org

![Screen Shot 2021-08-03 at 10 24 03 PM](https://user-images.githubusercontent.com/49563305/128126758-5a2fb709-40c0-4e36-a769-d61fbcc90479.png)
![Screen Shot 2021-08-03 at 10 24 14 PM](https://user-images.githubusercontent.com/49563305/128126760-1b58fd70-0eef-4e2a-b59d-4fbb9b6d5d23.png)

**Comment by Souad314** [comment]
I think what is breaking this path is having more than one owner selected.
Each time I select more than one owner, the rest of the choices don't come through (but also, I'm not sure that I've used my DS email to upload because it wasn't a curator account until recently).

**Comment by NicolasKieffer** [comment]
The problem come from "how the query is built". There is an "OR" operator between each condition (I could look to change it if necessary).
So in this case, it will return all documents owned "by at least one of 2 selected email addresses" OR "attached to the selected organization".

List of documents that may correspond to your conditions:
https://app.dataseer.ai/dataseer/documents/6104723f11b59e6b0d2e0b5d
https://app.dataseer.ai/dataseer/documents/6104725711b59e6b0d2e0bb0
https://app.dataseer.ai/dataseer/documents/6104726811b59e6b0d2e0c03
https://app.dataseer.ai/dataseer/documents/6104727611b59e6b0d2e0c56
https://app.dataseer.ai/dataseer/documents/6104727f11b59e6b0d2e0ca9

Note: one way to get your data might be to only select email addresses and use the "filter bar" to hide documents that are not attached to the "American Naturalist" organization (then use the next / previous buttons to navigate your results pages).

![image](https://user-images.githubusercontent.com/16922410/128429621-9d99fd9b-2ba9-4b27-aec1-4b2c3a60af25.png)

**Comment by NicolasKieffer** [comment]
**Note: It was a bug, I fixed it**
