### ISSUE TITLE
article metadata is still patchy

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#45]
Ideally the UI should locate the DOI of the document within the pdf and source the article metadata from CrossRef – this will make it more complete and better formatted.

If it can't find a DOI in e.g. a submission format article, the UI should go with its current method of finding title, authors within the text.

**Comment by NicolasKieffer** [comment]
@kermitt2 Metadata selectors need to be provided to be extracted successfully.

Selectors used are declared [here](https://github.com/kermitt2/dataseer-web/blob/master/lib/extractor.js#L54-L102)
Lines used to provide a selector for : [doi](https://github.com/kermitt2/dataseer-web/blob/master/lib/extractor.js#L98) or [pmid](https://github.com/kermitt2/dataseer-web/blob/master/lib/extractor.js#L101)
_Note : CSS selector syntax is used_

**Comment by kermitt2** [comment]
Yes I saw the selectors! I have the XPath expressions for the different metadata, see below. There are some constraints with the serialization, similar to author names, where a space or `;` must be inserted between fields as indicated.

```
# main fields
x_title = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title[@type="main"]'
x_publication_date1 = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:monogr/tei:imprint/tei:date[@type="published"]'
x_publication_date2 = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:publicationStmt/tei:date[@type="published"]'
```

If `x_publication_date1` xpath is null, then use the second one `x_publication_date2`

```
# identifiers
x_doi = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:idno[@type="DOI"]
x_pmid = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:idno[@type="PMID"]
x_pmcid = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:idno[@type="PMCID"]
```

```
# authorship
x_author_persons = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:monogr/tei:author/tei:persName'
x_author_organizations = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:monogr/tei:author/tei:affiliation/tei:orgName'
```

Regarding organizations (called institutions), a ` ; ` should be inserted between each `tei:orgName` content.

**Comment by NicolasKieffer** [comment]
@kermitt2 I can't extract `x_author_persons` or `x_author_organizations` with thoses xPath in my "samples" PDFs. Can you send me yours please?

**Comment by kermitt2** [comment]
Sorry @NicolasKieffer I made a stupid error, it's not `monogr` but `analytic`:

```
# authorship
x_author_persons = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:analytic/tei:author/tei:persName'
x_author_organizations = '/tei:TEI/tei:teiHeader/tei:fileDesc/tei:sourceDesc/tei:biblStruct/tei:analytic/tei:author/tei:affiliation/tei:orgName'
```

**Comment by NicolasKieffer** [comment]
Fixed in commit https://github.com/kermitt2/dataseer-web/commit/2991ec220fabbe6a9df396c97d76f8f715a1670d

**Comment by kermitt2** [comment]
There are still quite a lot of work to get it working. 

![Screenshot from 2020-04-27 20-29-02](https://user-images.githubusercontent.com/2340795/80512877-79c41680-897e-11ea-992b-7e65030f3bce.png)

- author list is not correctly serialized (no comma/separator between authors - I think it used to work)

- `Submitting Author` and `Submitting Author email` are currently not present in the TEI document because Grobid does not extract this information from the PDF (it's not present in the PDF and it's also not in the native XML). It's something that could be available only via a publishing platform, so  you can ignore these two fields for the moment. 

- we can ignore empty fields I think

- we could display a bit more metadata that are available: identifiers (DOI, PMID)

- for the affiliations, ideally we would like to present them as they are in the TEI: either coming with each author, or as a list of separate affiliations. To simplify we could always list them separated from the author, but then it's useless to list several times the same affiliation. In any case, either we list them as "Submitting author affiliations" or as "institutions", but not both 2 times.

**Comment by NicolasKieffer** [comment]
Would it be correct render?

![image](https://user-images.githubusercontent.com/16922410/80519790-d298ac80-8988-11ea-9f3c-fd2c818921b9.png)

**Comment by kermitt2** [comment]
Render looks good yes!

* I have errors with "undefined" in branch `fix-45` following this commit:

```
TypeError: /home/lopez/dataseer-web/views/documents/metadata.pug:42
    40|           div(class='col-12')
    41|             div(class='key d-inline font-weight-bold') Institutions : 
  > 42|             if document.metadata.author_organizations.length > 0
    43|               each val, index in document.metadata.author_organizations
    44|                 div(class='value d-block') #{val}
    45|             else
```

(also in `dataseer-web/views/documents/finish.pug`)

* "Journal" path is the path to the publisher - so you should rename it "Publisher": 

```
'journal': function($) {
        return $('TEI > teiHeader > fileDesc > publicationStmt > publisher').text();
      },
```  

Publisher is good to have too! 

The path to the journal name in TEI is as follow:

```
'journal': function($) {
        return $('TEI > teiHeader > fileDesc > sourceDesc > biblStruct > monogr > title[level=j] ').text();
      },
```

**Comment by NicolasKieffer** [comment]
> I have errors with "undefined" in branch fix-45 following this commit

Cause structure of data has changed. You need to upload file to get new structure.

I will fix path/properties names.

**Comment by NicolasKieffer** [comment]
@kermitt2 
What should i do in this case?

![image](https://user-images.githubusercontent.com/16922410/80620877-d854c780-8a46-11ea-9d0f-69f62481ed44.png)

More precise selector (ex : title[level=j type=main]) or display all of them (ex : separate by coma).

**Comment by timvines19** [comment]
The article metadata for published manuscripts still does not look great. For articles where Grobid finds a DOI, can we please display the following metadata:

Journal: 
Publisher:
Publication date:
DOI: 

Article Title: 
Authors: 
Author 1 (Affiliation)
Author 2 (Affiliation) 
...
[display maximum 4 authors], the fifth line can then be <em> et al.</em>


This is what DataSeer currently shows for an example article (http://app.dataseer.ai/dataseer/documents/5f29bd7e22361e1e48630949): 

![Screen Shot 2020-08-08 at 3 30 45 PM](https://user-images.githubusercontent.com/49563305/89720910-3ff6a900-d98c-11ea-9275-b266c0ff0485.png)

The information above all seems to be readily available as a JSON file from CrossRef's DOI API: 

https://api.crossref.org/v1/works/10.1021/acsomega.0c01690

**Comment by timvines19** [comment]
When a pdf has been directly uploaded and Grobid can't find a DOI (and therefore doesn't have access to the CrossRef record), we can just display:

Article Title:
Authors: 

There's still a space issue with showing the author names (there's no space after the comma separating the names, or between names and initials)

**Comment by timvines19** [comment]
Metadata in My Documents/All Documents is also messy: e.g. the title for this article

http://app.dataseer.ai/dataseer/documents/5f28b3c722361e1e48630946

is "6360−6374 Downloaded via 172.218.5.247 on" and the Journal is "UTC"

**Comment by NicolasKieffer** [comment]
Some renders of metadata view (not available on dataseer-dev yet) :

_Note : "Reload metadata" button is only used for development at the moment_

![image](https://user-images.githubusercontent.com/16922410/99473266-8922a580-294a-11eb-8de2-7a0e1f0657aa.png)

![image](https://user-images.githubusercontent.com/16922410/99473283-92ac0d80-294a-11eb-87b8-888f41753a4c.png)

![image](https://user-images.githubusercontent.com/16922410/99473299-9a6bb200-294a-11eb-81b8-72d001e8c5ad.png)

![image](https://user-images.githubusercontent.com/16922410/99473319-a3f51a00-294a-11eb-81d6-1a26de999346.png)

**Comment by timvines19** [comment]
wow, looks really good
