### ISSUE TITLE
Special Character displays are wonky

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#458]
Even the apostrophe in Parkinson's Disease:

![image](https://user-images.githubusercontent.com/81999469/129622461-d98fd5b0-916e-47e3-b46b-b0ac720d25de.png)

These other one's should be the Greek letter alpha

**Comment by NicolasKieffer** [comment]
Encoding bug fixed, I'm trying to find a way to "cure" the existing data.

**Comment by NicolasKieffer** [comment]
Should be fixed now
