### ISSUE TITLE
Sentence selection issues

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#461]
Line 412 of this document has some major sentence selection problems

https://app.dataseer.ai/dataseer/documents/611a663a0e0b06193e1a2008/datasets

The sentence from line 412 to 414 is selectable and a dataset can be added. 
The fragment starting 'Porter et al' on lines 414-416 can be highlighted but no dataset can be added. 
Lines 417-420 can't be selected, and the fragment on line 421 is joined to lines 414-416. 
The two sentences starting on lines 421 can be selected but no dataset can be added. 
The sentence from lines 424 to 428 is joined to the sentence lines 412-414

The sentences from lines 239-250, lines 320-326, and lines 379 to 385 are not selectable, neither is the end of the sentence line 395-398

**Comment by NicolasKieffer** [comment]
> The sentence from line 412 to 414 is selectable and a dataset can be added.

dataseer-ml tag it as "sentence", so it will work.
![image](https://user-images.githubusercontent.com/16922410/130241208-0f4580f8-cd31-4007-b796-961cd7f08478.png)

> The fragment starting 'Porter et al' on lines 414-416 can be highlighted but no dataset can be added.

I can't yet explain why this bug is occurring (but I understand why you can't add a dataset). I will patch it as soon as possible.
Note: only a few sentences are apparently affected.

> Lines 417-420 can't be selected, and the fragment on line 421 is joined to lines 414-416.

dataseer-ml do "extract" lines 414-416 as a "table" (not as a "sentence")
![image](https://user-images.githubusercontent.com/16922410/130242473-d0b55703-e03b-4ade-a02f-cb0740edaab6.png)

> The sentences from lines 239-250, lines 320-326, and lines 379 to 385 are not selectable, neither is the end of the sentence line 395-398

This should be selectable, I have to find out why it isn't.
![image](https://user-images.githubusercontent.com/16922410/130244386-624e3223-6a64-4acc-a40e-7dc4804efca6.png)

**Comment by NicolasKieffer** [comment]
> This should be selectable, I have to find out why it isn't.
> ![image](https://user-images.githubusercontent.com/16922410/130244386-624e3223-6a64-4acc-a40e-7dc4804efca6.png)

**The "sentence area" detection (done by dataseer-ml) seems not working on this case.**

The text is indeed "extracted" (the `<s>` element contains it), but the area (coords property) is not the outline of the sentence but of a single "chunk/word".

![image](https://user-images.githubusercontent.com/16922410/130247744-3d7bc358-37a6-4c55-8542-03ac6d0749ef.png)
![image](https://user-images.githubusercontent.com/16922410/130247412-39592fca-5a4d-4077-9ea7-f3668f0199ef.png)

The text of all sentences looks correct, but the "areas" do not.

![image](https://user-images.githubusercontent.com/16922410/130247377-1c65e6e6-79ff-4ecc-b19e-7f798d6bc255.png)

![image](https://user-images.githubusercontent.com/16922410/130248272-d79bb319-5805-405a-b62a-2235189d3ba8.png)
![image](https://user-images.githubusercontent.com/16922410/130248371-dbb4b726-06f9-4dd0-b324-aa5cd36d6671.png)


![image](https://user-images.githubusercontent.com/16922410/130248208-3ff6ab63-6554-45fe-adc0-d662a42d2043.png)
![image](https://user-images.githubusercontent.com/16922410/130248435-0d9d362a-aa11-4389-990f-f2fbfbbf834d.png)

**Comment by kermitt2** [comment]
For the last sentences, this is the same issue as #441 
Sentence segmentation is good, but the realignment with tokens after segmentation has a problem and the bounding box built for the sentence is incorrect (only contains a few layout tokens...).

This comes from grobid, to keep track of it, https://github.com/kermitt2/grobid/issues/811

I will have a look soon.

**Comment by kermitt2** [comment]
This is fixed in Grobid... for instance for this sentence datatset-9 we have now good complete bounding box coordinates: 

```
                    <s coords="16,105.98,540.27,428.32,10.80;16,72.02,567.87,436.34,10.80;16,72.02,595.38,429.74,10.91;16,72.02,623.10,356.91,10.80">Habitat isolation arises in crossbills because individuals preferentially forage on the most profitable conifers 
                        <ref type="bibr" coords="16,163.22,567.87,78.82,10.80" target="#b2">(Benkman 1987)</ref>, and the conifers that are most profitable depend on an individual's bill morphology 
                        <ref type="bibr" coords="16,212.86,595.38,74.62,10.91" target="#b4">(Benkman 1993</ref>
                        <ref type="bibr" coords="16,295.87,595.38,25.92,10.91" target="#b10">(Benkman , 2003))</ref>, resulting in matching habitat choice 
                        <ref type="bibr" coords="16,72.02,623.10,74.78,10.80" target="#b6">(Benkman 2017</ref>; see 
                        <ref type="bibr" coords="16,173.52,623.10,149.09,10.80">Edelaar et al. 2008, Berner and</ref>
                        <ref type="bibr" coords="16,325.61,623.10,98.17,10.80" target="#b15">Thibert-Plante 2015)</ref>.
                    </s>
```

same for dataset-10 and so on:

```
                    <s coords="16,432.05,623.10,90.67,10.80;16,72.02,650.70,465.17,10.80;16,72.02,678.30,459.40,10.80;16,72.02,705.90,223.47,10.80">Habitat isolation is strong where only ponderosa pine or lodgepole pine occur such as in extensive monotypic stands of ponderosa pine in northern Arizona where only ponderosa pine crossbills are regularly found in large numbers 
                        <ref type="bibr" coords="16,155.54,705.90,134.79,10.80" target="#b13">(Benkman and Young 2020)</ref>.
                    </s>
```

After merging the PR in Grobid, it requires then rebuilding `dataseer-ml` with the fix and redeploy :/
