### ISSUE TITLE
Text Selection Bug - footer selection with sentence text displayed

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#475]
There are some major text selecting issues with this article: 
[Vangheluwe Si et al published ijms-22-02689-v3.pdf ](https://app.dataseer.ai/dataseer/documents/6127e07e28726d720253b07b?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjEyN2UwN2UyODcyNmQ3MjAyNTNiMDdiIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjMwMDAzMzU4LCJleHAiOjE2MzI1OTUzNTh9.N7EpD7u_RXgvgd0XxMn1X6m_0ZHgyxF_Uue5E-BDoRM)

https://www.loom.com/share/3ab2093755d94cfab9bcb78282f36384

But in the pdf itself it is hard to select text, it has some weird things going on with text selection and isn't accessible through a link, it has to be accessed through your own drive:
ijms-22-02689-v3.pdf 
![image](https://user-images.githubusercontent.com/81999469/131027985-3b8230f2-05e1-4528-a992-21b0cb8b8f7a.png)

The article is available online at: 
https://www.mdpi.com/1422-0067/22/5/2689/htm

**Comment by timvines19** [comment]
That is wonderfully bizarre. No need for any special action unless we run into this more often...
