### ISSUE TITLE
Article won't load in DS Validation

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#476]
I uploaded the topmost one from the [DS pdf](https://app.dataseer.ai/dataseer/api/files/612a75c828726d720253f620/) to see if that would change anything.
![image](https://user-images.githubusercontent.com/81999469/131372725-fd5b193b-7828-4689-9f9a-e21119dcef9e.png)

https://app.dataseer.ai/dataseer/documents/612a75c828726d720253f61a/datasets

The article is forever in this state:
![image](https://user-images.githubusercontent.com/81999469/131372893-d0d1a533-34e1-40b7-b0d6-da7576e250ea.png)

There was another one like this a few weeks ago: [60334_R3 - broken](https://app.dataseer.ai/dataseer/documents/611fe01aaf4ff741e02bb0cf/)
[60334_R3 - fixed](https://app.dataseer.ai/dataseer/documents/611fcd97af4ff741e02ba81c?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjExZmNkOTdhZjRmZjc0MWUwMmJhODFjIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjI5NDc0MjIwLCJleHAiOjE2MzIwNjYyMjB9.msdq5WyMUwz887tJv5TDrJBs0ZqAhS_MOjvOoJTL3zQ)

**Comment by NicolasKieffer** [comment]
This document should be fixed now.

This bug is related to : https://github.com/DataSeer/dataseer-web/issues/472

**Comment by Souad314** [comment]
Yes, it loaded now! Thank you so much especially for such a quick reply!

**Comment by NicolasKieffer** [comment]
(Fixed : c.f. https://github.com/DataSeer/dataseer-web/issues/472)
