### ISSUE TITLE
 'All Documents' to have a 'Date uploaded' column?

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#48]
Could the 'All Documents' and 'My Documents' have a 'Date uploaded' column? I see that space is tight but maybe the URL that's displayed could be shortened?

**Comment by NicolasKieffer** [comment]
**_Updates available on branch [fix-48](https://github.com/kermitt2/dataseer-web/tree/fix-48) . This is note the final render_**

What would be the best render?

Render 1 : _(available at /documents)_
![image](https://user-images.githubusercontent.com/16922410/76026540-41302f80-5f2f-11ea-8912-624b2d363e31.png)

Render 2 : _(available at /MyDocuments)_
![image](https://user-images.githubusercontent.com/16922410/76026563-51480f00-5f2f-11ea-8d69-c3d27d45907e.png)

Note : Putting document Url on date and removing ids would free up space for others columns.
_(search by id would be still available)_

**Comment by timvines19** [comment]
Render 1 looks best to me

**Comment by kermitt2** [comment]
With branch fix-48 the date is displayed fine, but it appears only for newly loaded documents. 
For the existing one prior to the future merge, we have `NaN-NaN-NaN`. It might good to catch the invalid field and display nothing in that case.

**Comment by NicolasKieffer** [comment]
This feature is now in [branch 109](https://github.com/DataSeer/dataseer-web/tree/fix-109) (c.f. PR https://github.com/DataSeer/dataseer-web/pull/120)
