### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#482]
https://www.loom.com/share/a195c405e32e40caab2b5dfc138d5dc1

More info:

- It doesn't matter that it's Chrome, it doesn't let me login on Edge either
- It doesn't work on either of my Dell computers
- It doesn't work for the gmail nor dataseer email
- I can't login to the production server either
- I reset my password
- I restarted both computers

- I can login using other people's information

**Comment by NicolasKieffer** [comment]
@Souad314 It should be fixed now

**Comment by Souad314** [comment]
Yes! I can login, thank you so much
