### ISSUE TITLE
Issue updating Hypothesis annotation

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#500]
There's an error when trying to send the annotation to the hypothesis account on bioRxiv:

https://www.loom.com/share/cb2ef58ee58148289fa9deccc5122c4f

This is the bioRxiv link I used: https://www.biorxiv.org/content/10.1101/2021.09.20.461037v1

Here's the DataSeer report: https://app.dataseer.ai/dataseer/documents/6148d0b01d5e530ed5a73870/finish

**Comment by NicolasKieffer** [comment]
Should be fixed now (I have created the annotation in production while testing the patch)
