### ISSUE TITLE
Build Google Spreadsheet - Journal Version

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#539]
AmNat Reports are much simpler than the ASAP one, we were wondering if you could make another "Build Google Spreadsheet report" button that creates a Sheets report like this template: 
https://drive.google.com/file/d/1DAvJaOyh1zf-R4abbU-7Kz0BXTpFcN7m/view?usp=sharing
(also found in the "Template and Example Reports" folder in the "Tech Development" shared folder in the DataSeer drive)
Here's an example of a filled out report - just for reference (also in that folder): 
https://docs.google.com/spreadsheets/d/1uKHSxbLYvHqF1FRqNz39PS3GVWTGe0-SbdHA_5EuooI/edit?usp=sharing

This sheet report is only a single tab, and it is much more synced to what's going on in the DS interface. It also only requires datasets and code information (no protocols or lab materials), and doesn't require links to the DS Wiki!

It would also help us organize it better if the created sheet's name was the file upload name, for example, the filled out example report would be called "60631_R1" if generated from the DS interface instead of "6196e50650e6c60656ac9dd9"
DataSeer Link to [60631_R1](https://app.dataseer.ai/dataseer/documents/6196e50650e6c60656ac9dd9?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjE5NmU1MDY1MGU2YzYwNjU2YWM5ZGQ5IiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjM3Mjc5MDM3LCJleHAiOjE2Mzk4NzEwMzd9.7M7UyRry1bl24ZlSglHHtv78t8RFEFmGRzs7HPizDvg) (on finish page)

Do you think it would be possible to create a sheet button/create sheets for this type of report?

**Comment by NicolasKieffer** [comment]
> It would also help us organize it better if the created sheet's name was the file upload name, for example, the filled out example report would be called "60631_R1" if generated from the DS interface instead of "6196e50650e6c60656ac9dd9" DataSeer Link to [60631_R1](https://app.dataseer.ai/dataseer/documents/6196e50650e6c60656ac9dd9?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjE5NmU1MDY1MGU2YzYwNjU2YWM5ZGQ5IiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjM3Mjc5MDM3LCJleHAiOjE2Mzk4NzEwMzd9.7M7UyRry1bl24ZlSglHHtv78t8RFEFmGRzs7HPizDvg) (on finish page)

Regarding the name of the report: would this kind of name "60631_R1 (6196e50650e6c60656ac9dd9)" work for you?
The DataSeer ID ensures that there are no duplicate file names in the drive folder (even if several files have the same name in DS).

> Do you think it would be possible to create a sheet button/create sheets for this type of report?

Absolutely, I will implement it (one button for "ASAP", another for "AmNat").

**Comment by Souad314** [comment]
"60631_R1 (6196e50650e6c60656ac9dd9)" Yes that's perfect! That explanation makes a lot of sense.

This is wonderful! You're the best!! Thank you so much.
