### ISSUE TITLE
Validation Page Issues

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#563]
I can't add any new datasets in DS. 
I've tried:
- Log out, close browser
- Not Chrome
- Different account
- Different computers
- Refresh token of document
- Re-Open Document

Also to note:
- The DEV server works normally to add datasets

https://www.loom.com/share/c48ed25ca30146e08319981b6226bec4

- Whole Page Text Selection button doesn't work for Tim, but it works for me (I just can't add any datasets)

**Comment by NicolasKieffer** [comment]
This should be fixed now.

Note: the dataseer-ml service crashed (on the production server), so adding new datasets (and uploading new documents surely as well) did not work anymore.

**Comment by Souad314** [comment]
Thank you! It's working again :)
