### ISSUE TITLE
Journal Report Template Update 01/2022

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#578]
The updated [template report](https://docs.google.com/spreadsheets/d/1LyO44S4wtswxM-8d8Sx76kAZnk-BSqKRBSDm8u_4nns/edit?usp=sharing) for AmNat reports is ready for implementation! 

Mostly changes to colours with some formatting and input position changes

Issue:
- There was an issue with the old report missing the information in columns E and F for the Code Section (if there was a link in DOI or Comments in the interface, it wouldn't show up in the report)

![image](https://user-images.githubusercontent.com/81999469/150884412-677219ca-3ec3-42ba-a630-a0724beb58d1.png)
![image](https://user-images.githubusercontent.com/81999469/150884292-e4e746ee-9169-459c-a425-2f1fdaaf0d81.png)
[xxxxx_Rx.pdf](https://app.dataseer.ai/dataseer/documents/61ef36a655b9f72841993833?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb2N1bWVudElkIjoiNjFlZjM2YTY1NWI5ZjcyODQxOTkzODMzIiwiYWNjb3VudElkIjoiNjA0M2U0MDg3Yzg4NDg0OTZkZGUzNzA4IiwiaWF0IjoxNjQzMDY3MTAwLCJleHAiOjE2NDU2NTkxMDB9.xWQ-WIqCRCpmttBPdvBEnft6XZoqg4Z01KqP6v9VT9c) (DS Interface link to article corresponding to 01/22 template inputs)
[xxxxx_Rx.pdf (61ef36a655b9f72841993833)](https://docs.google.com/spreadsheets/d/13mAjT6zgS1lKHsOMjj-imq6POjYv9VrSo-az4X7Dw_M/edit?usp=sharing) (auto-generated report to show issue)

**Comment by NicolasKieffer** [comment]
This should be fixed now
