### ISSUE TITLE
Formatting of information on metadata page needs improvement

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#62]
For example, there are no spaces between the author names in this example

![Screen Shot 2020-03-09 at 2 47 09 PM](https://user-images.githubusercontent.com/49563305/76260824-e5f38b00-6215-11ea-883e-4d921eb4f3b9.png)

**Comment by NicolasKieffer** [comment]
will be fixed in issue https://github.com/kermitt2/dataseer-web/issues/45
