### ISSUE TITLE
Funder (ASAP) Report - Minor Bugs

### ISSUE THREAD

**Issue by Souad314** [DataSeer/dataseer-web#657]
There are a couple minor issues with the output for the ASAP reports:
1. Detailed Report Tab - formatting issue
https://www.loom.com/share/722184edf2734064a577734651035c43

I modified some columns a while ago to accommodate the inputs in the interface, but the changes are only applying to the first entry  - the lab materials datatype isn't there for the rest of the entries. I'm very sorry if any of these are my fault.

![image](https://user-images.githubusercontent.com/81999469/162469770-490275d0-0701-4257-a09e-0cff6a2d436a.png)
![image](https://user-images.githubusercontent.com/81999469/162469825-8e3a3d19-8642-426b-bed6-013a7fa65762.png)

2. Summary Tab - Action Required
https://www.loom.com/share/3ec15a7680b44efd8bf1e68c6ab0316f

The function in this table isn't working, it's always "No"
![image](https://user-images.githubusercontent.com/81999469/162470298-e3b03e0b-67a8-4f58-b122-0852177e80a0.png)
![image](https://user-images.githubusercontent.com/81999469/162470407-4f27b17e-ce51-4179-b8ff-7aa91b76fc4e.png)
![image](https://user-images.githubusercontent.com/81999469/162470352-ad84a89b-3394-4d16-8c8b-8e932fa2a31f.png)
![image](https://user-images.githubusercontent.com/81999469/162470464-0fcf1f6b-daac-4583-9b0e-c0c88ff7bd6d.png)

**Comment by NicolasKieffer** [comment]
The problem with the "merging of cells" should be solved.
I will work on the problem with the "Summary - Action Required" tab.
