### ISSUE TITLE
display annotated pdf instead of processed xml?

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#74]
The main problem with the UI at the moment is the inconsistencies in how it displays the text (e.g. main document text appearing in the figure captions, #40). 

Would it be plausible for Grobid to parse the pdf, detect data sentences etc, and have the UI display an annotated pdf? Since the pdf is correctly structured that would ensure that everything is displayed in the correct place, but I see a few challenges:

1) refinding the correct sentences in the pdf to highlight them
2) dealing with two column pdfs or pdfs with very wide borders – these may be hard to fit into the current UI screen. Maybe there could be a zoom in/out function for the pane containing the pdf, and/or a horizontal scroll bar?

**Comment by timvines19** [comment]
See e.g. this Data Note: http://cloud.science-miner.com/dataseer/documents/5e7bc377b2924f373d23e4a2

The Data Description paragraph stops halfway through and the rest of the paragraph text does not appear anywhere in the UI (see attached pdf)
[s13104-020-04964-z.pdf](https://github.com/kermitt2/dataseer-web/files/4383517/s13104-020-04964-z.pdf)

**Comment by kermitt2** [comment]
Yes @timvines19 ! this was an option we discussed only superficially. Grobid keeps track of the coordinates of each segmented sentence so we could offer a view of the PDF (a fourth one after `full text`, `section`, `paragraph`) where the sentences will be clickable over the PDF layout as they are now with the TEI XML full text. No more structure mess :)

For the backend (dataseer-ml), there would be minor change I think (just propagate coordinates from Grobid, and add the page size which are missing currently in the XML see this [issue](https://github.com/kermitt2/grobid/issues/523) - necessary for the scaling), the impact is more important on the application as you indicate indeed:

- it will only work for PDF input

- the documents in XML format stored in the current DB have no coordinates so, the PDF view will be supported only for new documents

- we need to store and preserve the PDF (so the MongoDB will be much larger)

- the display panel will likely be too small for a PDF page view and for interacting easily with it. One possibility is to change the overall layout of the application to have the third panel (list of datasets in the documents) horizontal above the document view. We would gain some horizontal space to display the page in width and have a larger panel for the PDF.

In case of a sentence present on both columns, I think there is no easy solution, the user will need to scroll a bit to read a complete sentence 

- the internal mechanism for the selection of the sentence will have to be rewritten 

Overall it would be definitively very cool to have, and Grobid is already doing the most complicated part with all the PDF parsing, bounding box coordinates and XML alignment, but it remains quite a lot of development work for the UI. I will try to estimate the development effort.

**Comment by kermitt2** [comment]
@NicolasKieffer grobid and dataseer-ml have been updated to better support sentence segmentation and provided coordinates at sentence levels, as a list of bounding boxes. 

The TEI XML result has sentence elements as before for the textual content with coordinates as follow: 

```xml
            <div subtype="dataseer">
                <head>LIFESTYLE TRIALS IN PEOPLE WITH IGT TO PREVENT PROGRESSION</head>
                <p>
                    <s coords="2,39.68,452.07,164.01,10.14;2,39.68,464.26,164.04,8.95;2,39.68,475.26,164.02,8.95;2,39.68,486.26,164.03,8.95;2,39.68,497.26,164.04,8.95;2,39.68,508.26,140.98,8.95">TO TYPE 2 DIABETES -In the early randomized intervention study in Malmö hus, Sweden 
                        <ref target="#b18" type="bibr">(19)</ref>, lower rates of type 2 diabetes was found in IGT men randomized to dietary intervention compared with those who received no therapy.
                    </s>
                    <s coords="2,184.27,508.26,19.44,8.95;2,39.68,519.26,164.00,8.95;2,39.68,530.26,164.04,8.95;2,39.68,541.26,64.25,8.95">More recently, several trials have tested the efficacy of lifestyle intervention in prevention of type 2 diabetes.</s>
                </p>
```

Sentence coordinates are provided for all the sentences of the document, including figure/table captions. The documentation of the coordinate format is [here](https://grobid.readthedocs.io/en/latest/Coordinates-in-PDF/#coordinates-in-teixml-results). They are strictly equivalent to the JSON format. For example `"1,53.80,194.57,58.71,9.29"` indicates one bounding box with attributes page=1, x=53.80, y=194.57, w=58.71, h=9.29, so in JSON `{  "p": 1, "x": 53.80, "y": 194.57,"w": 58.71,  "h": 9.29}`.

As documented under `/TEI/facsimile` we have the "dimension" of every pages to scale the coordinates given in the TEI document. 

So after translating the XML coordinates into the usual JSON format, the coordinates can be used with the usual javascript methods and PDF.js. 

The dev dataseer-ml server has been updated to test the new dataseer-ml version: http://cloud.science-miner.com/dataseer-ml-dev/

A requirement is now that the PDF that has been sent for processing to the dataseer-ml service will need to be saved with the corresponding TEI XML result in mongo (GridFS I guess) and dataseer-web will need to expose with a (secure) service this PDF for display. Without available PDF, the PDF tag view should be be made unavailable and defaulting to the normal document text view.

**Comment by timvines19** [comment]
Looks great! 

1) Please bevel the corners of the bounding box to match the style of the bar at the top
2) It can take a few seconds to load, so a 'loading' icon would be great so that users know that something is happening
3) pretypeset articles can be double spaced, and currently the sentence can't be selected unless the cursor is actually on the text. Maybe change it to sentence selection whenever the cursor is within the bounding box?

**Comment by timvines19** [comment]
The bounding box is also a little off in some pdfs: 
https://cloud.science-miner.com/dataseer-dev/documents/5fa302c09a98aa090105af92

![Screen Shot 2020-11-04 at 12 05 04 PM](https://user-images.githubusercontent.com/49563305/98162535-5ed6df80-1e96-11eb-9b02-f7cdfa16a82e.png)


https://cloud.science-miner.com/dataseer-dev/documents/5fa1a4dd8680a60fba2e5f23

![Screen Shot 2020-11-04 at 12 08 21 PM](https://user-images.githubusercontent.com/49563305/98162596-71e9af80-1e96-11eb-8727-c67be81398ac.png)
