### ISSUE TITLE
Create a Docker for easier deployment

### ISSUE THREAD

**Issue by kermitt2** [DataSeer/dataseer-web#77]
The install of dataseer-ml is quite complicated because it is a mixture of java (Grobid and dataseer-ml services) and python (deep learning parts plus synchronization with the wiki), including the JEP for the JNI call to the deep learning process. This is both error prone and time consuming.

To simplify the deployment, we could create a docker image of at least dataseer-ml (see Grobid docker). Optionally we could add dataseer-web in the image.

**Comment by timvines19** [comment]
Complete so closing this issue
