### ISSUE TITLE
Focus data sentence detection on Methods sections

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#82]
Sentences in the introduction often say what data were collected for an article (e.g. dataset 1 here: http://cloud.science-miner.com/dataseer-dev/documents/5e78cc6e46fdf43e729d5b6c), but these are 'false positives' because the Methods will always contain the same datasets. 

The algorithm should ideally locate the Methods section and focus its initial search there. This should also help when the Methods section is at the end of the article, as currently false positive sentences in the text before the Methods are often highlighted. 

This change should help improve how DS works with Nature style articles (which have the Methods at the end) – I've labelled it 'Needed for Production' as this change should ideally be in place once they start testing.

**Comment by timvines19** [comment]
Here's three pdfs that were producing some false positives in the introduction and elsewhere:

[acsomega.0c00772 (Thuy et al).pdf](https://github.com/DataSeer/dataseer-web/files/5257060/acsomega.0c00772.Thuy.et.al.pdf)
[acsomega.9b00514 (Tolley et al).pdf](https://github.com/DataSeer/dataseer-web/files/5257083/acsomega.9b00514.Tolley.et.al.pdf)
[acsomega.0c01690 (Zhou et al).pdf](https://github.com/DataSeer/dataseer-web/files/5257101/acsomega.0c01690.Zhou.et.al.pdf)

**Comment by kermitt2** [comment]
So the initial document, PDF [jeb.13055.pdf](https://github.com/DataSeer/dataseer-web/files/5305712/jeb.13055.pdf), is working fine, I think, with the implemented focus. 

Both acsomega.9b00514 (Tolley et al).pdff and acsomega.0c01690 (Zhou et al).pdf have no explicit method section, so the focus is not happening. However in both cases, we have an "experimental" section which looks similar. So the idea could be that if no explicit "method" section is found, we still apply a similar focus on the "experimental" section. 

For the first one (Thuy et al.), bad luck, we have an explicit method section, but Grobid is not detecting the section title of this method section, so the focus also doesn't apply. This means that some training data for the Grobid full text models for "method" sections should probably be added - but it could be fixed easily anyway by additional check.

**Comment by timvines19** [comment]
Would be great to deploy this to the SN server. the NPJ Breast Cancer articles all have a Methods section, the ones from BMC Research Notes have a 'Data Description' section. BMC RN articles are really short and don't really have an intro or results/discussion, so the scope for false positives is lower here.

**Comment by timvines19** [comment]
Add 'Experimental Data' as another type of 'Methods section'
