### ISSUE TITLE
carriage returns in wiki advice

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#88]
when advice on wiki contains carriage returns, text after return does not appear in UI

Wiki advice:

![Screen Shot 2020-05-27 at 2 16 43 PM](https://user-images.githubusercontent.com/49563305/83073199-e20d2300-a024-11ea-8180-e7ca870fe3c5.png)

UI advice:
![Screen Shot 2020-05-27 at 2 15 53 PM](https://user-images.githubusercontent.com/49563305/83073202-e2a5b980-a024-11ea-95bb-de320aabb967.png)

**Comment by NicolasKieffer** [comment]
I can not reproduce this bug (on master branch). All data seems to be there (without carriage returns)

![image](https://user-images.githubusercontent.com/16922410/85021280-f353d600-b171-11ea-8278-5f5942d82da4.png)

**Comment by timvines19** [comment]
@NicolasKieffer this problem still persists. It's particularly an issue for 'Tabular Data:Subject Data Table' because that has multiple paragraphs on the wiki: https://wiki.dataseer.io/doku.php?id=data_type:tabular_data:research_subjects

Only the first paragraph displays in the UI: 

![Screen Shot 2020-11-29 at 10 01 43 AM](https://user-images.githubusercontent.com/49563305/100549825-2672b900-322a-11eb-95ae-de805ee314c7.png)

**Comment by timvines19** [comment]
would be great to get this issue fixed soon as it always appears when I'm showing the UI to people
