### ISSUE TITLE
Ensure GDPR compliance

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#91]
The requirements:
- ask the users an explicit consent about how the personal information will be used by the service, it has to be clearly expressed. So typically for us, it would include the usage of a cookie and identifiers to allow the normal functionalities of the service
- offer the possibility to correct and remove any personal information on request
- ask for a consent when a third party is involved with data. So in particular if we send the data to SpringerNature, it has to be clear and we need a user consent for that 
- the web server should include a privacy notice explaining what we do with the information we receive (on the website and on the server)
- data transmission and stored data need to be secured “by design", so it means SSL and normally encrypting the content of the database (both are not done at the moment)

**Comment by NicolasKieffer** [comment]
Can user "decline consent" and still use dataseer-web app??

**Comment by timvines19** [comment]
I don't think so, but @kermitt2 might know better. They should be able to easily reverse their 'decline consent' choice though

**Comment by NicolasKieffer** [comment]
I need more infos:

Which contact address? same as dataseer.ai (https://dataseer.ai/contact/) or new dedicated email to dataseer-web?

List of all companies that will have access to the data (@timvines19)

Server location ("Dataseer server", "science miner server"?) (@kermitt2)

**Comment by kermitt2** [comment]
> Server location ("Dataseer server", "science miner server"?) (@kermitt2)

DataSeer servers are hosted by Linode, LLC and are located in Atlanta, Georgia, USA.

**Comment by timvines19** [comment]
the email address can be info@dataseer.ai
The only company with full access to the data is DataSeer Research Data Services Ltd
