### ISSUE TITLE
users who are already signed in who click 'sign up' hit an error

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#92]
It says "Your current role do not grant access to this part of website"

Would be better if they went to 'My Documents' instead

![Screen Shot 2020-06-12 at 10 34 59 AM](https://user-images.githubusercontent.com/49563305/84531139-f6922200-ac98-11ea-80f0-33804b7b2529.png)

**Comment by kermitt2** [comment]
A question - if the user cannot access the page, my impression is that it usually means that they are not logged in? In this case, they could not access the "My Documents" page and it would be better to re-route to the login page ?

**Comment by NicolasKieffer** [comment]
This is case user already have an account and try to access "sign-up" form (or this should not be possible).
Note : There is (and was) no direct link available but it can be reached by URL.

**Comment by kermitt2** [comment]
ok I see ! 

I was thinking about the case a user logout from the application but still try to access then to a document via the document url that he might have saved (e.g. http://cloud.science-miner.com/dataseer-dev/documents/5e4fc5fe6dd0aa64382333b0). He could be redirected first to the login page, and then forwarded to the document page. But it's another case than the one reported as you say.

**Comment by NicolasKieffer** [comment]
I will implement it then.

**Comment by NicolasKieffer** [comment]
Then I will implement this case too.
