### ISSUE TITLE
add CAPTCHA or similar to prevent robot sign ups

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#94]
Once the website becomes more public then we'll get robots signing up and uploading crap. We need to add a CAPTCHA or similar to prevent this.

**Comment by NicolasKieffer** [comment]
Feature available on branch [captcha](https://github.com/kermitt2/dataseer-web/tree/captcha)

**Comment by kermitt2** [comment]
Looks good, merged and deployed at http://cloud.science-miner.com/dataseer-dev

**Comment by kermitt2** [comment]
@NicolasKieffer I re-open the issue because after merging with master, captcha does not appear to work anymore. Possibly the merging overwrite something? There is also no error message and I don't see any call to https://www.google.com/recaptcha/api/ anymore. If you could have a look ? Thanks

**Comment by NicolasKieffer** [comment]
Captcha is only used on /signup page (when user create an account, captcha badge visible on bottom left)

on https://cloud.science-miner.com/dataseer-dev/signup : it seems to be an error with keys & domain name.

![image](https://user-images.githubusercontent.com/16922410/93807134-7ccfe400-fc4a-11ea-828f-41f1f8bbc783.png)
![image](https://user-images.githubusercontent.com/16922410/93807538-0f708300-fc4b-11ea-9cca-8849cc2cb0da.png)

on https://app.dataseer.ai/dataseer/signup : it seems this is not yet implemented here (didn't found public API key into signup form)

**Comment by kermitt2** [comment]
Thank you @NicolasKieffer ! It works, I forgot it was only on the signed up page (not sign in) and I inverted the dataseer.ai key pairs with the ones of science-miner.com :) 
app.dataseer.ai is not running yet the master, so no captcha for the moment.
