### ISSUE TITLE
replace DataSeer Logo on UI

### ISSUE THREAD

**Issue by timvines19** [DataSeer/dataseer-web#95]
We've a new logo, and we need to have the new one on there by Tuesday. New logo attached

![DataSeerLogo_Color_Horz_PNG_BIG](https://user-images.githubusercontent.com/49563305/85310551-f815d400-b468-11ea-9d8b-9d0a36b6975e.png)

**Comment by NicolasKieffer** [comment]
Render :
![image](https://user-images.githubusercontent.com/16922410/85401890-10feb200-b55b-11ea-9ffe-fe808513e510.png)

**Comment by timvines19** [comment]
has this been implemented on the production site? Still seeing the old logo there

**Comment by kermitt2** [comment]
Well, it's not just changing the logo bitmap, all the color codes of the pages need to be modified too (they are consistent with the previous logo colors). Is there a graphic resource package coming with the new logo, with color codes and possibly other "design" element like for the buttons and/or fonts to be used?

**Comment by timvines19** [comment]
there will be a graphic resource package available this week or next.

**Comment by timvines19** [comment]
basic style info:

Text colour: #3a3a3a
Theme colour: #0274be
Link colour: #0274be
Link hover colour:  #3a3a3a

header font: https://fonts.google.com/?query=quicksand
text font: TBC

**Comment by kermitt2** [comment]
Updates have been made with branch fix-95, including new favicon.ico. I also added a indication "beta" next to the logo.

**Comment by kermitt2** [comment]
@timvines19 updates are deployed at http://cloud.science-miner.com/dataseer-dev

**Comment by timvines19** [comment]
Thanks - looks cool. Since the font is wider and we've added 'Organisations' the header bar is getting a bit crowded. Can the logo move up a bit relative to the menu text? Or maybe shrink the font or adjust the kerning on the menu items so that it doesn't come across as much?

![Screen Shot 2020-09-01 at 10 23 29 AM](https://user-images.githubusercontent.com/49563305/91885783-3126ad80-ec3d-11ea-9319-83b140e39739.png)

**Comment by kermitt2** [comment]
![Screenshot from 2020-09-02 03-32-46](https://user-images.githubusercontent.com/2340795/91922142-7a264280-eccd-11ea-8043-45593f04a554.png)

Variation also at  http://cloud.science-miner.com/dataseer-dev

**Comment by timvines19** [comment]
I talked to the designer and here's the conclusions:
1) this is only a problem for curators, as they have lots of menu items. It doesn't affect standard users at all (see screenshot), and they're the group we care most about.

![Screen Shot 2020-09-07 at 2 39 31 PM](https://user-images.githubusercontent.com/49563305/92418259-6f2f4000-f11b-11ea-93a2-950908261111.png)

2) Uzi thought that the logo was too big – he suggests doubling the size of the 'BETA' then halving the size of the logo overall. It's much smaller relative to the text on the main DataSeer website

![Screen Shot 2020-09-07 at 3 07 20 PM](https://user-images.githubusercontent.com/49563305/92418334-dc42d580-f11b-11ea-85cc-9692cf3c2352.png)

**Comment by kermitt2** [comment]
1. Sure but then I guess the solution is to have 2 logos loading depending on the user profile

2. Smaller logo:

![Screenshot from 2020-09-14 12-08-55](https://user-images.githubusercontent.com/2340795/93073367-17488a00-f683-11ea-8f9b-4cb7d188c588.png)

**Comment by timvines19** [comment]
Thanks - this is a good solution
